// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: AbnfLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated AbnfLexer lexer.
pub struct AbnfLexer {
    inner: RegexLexer,
}

impl AbnfLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("ABNF");
        inner.aliases = vec![
            "abnf",
        ];
        inner.filenames = vec![
            "*.abnf",
        ];
        inner.mimetypes = vec![
            "text/x-abnf",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r";.*$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"(%[si])?"[^"]*""##, Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"%b[01]+\-[01]+\b", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"%b[01]+(\.[01]+)*\b", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"%d[0-9]+\-[0-9]+\b", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"%d[0-9]+(\.[0-9]+)*\b", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"%x[0-9a-fA-F]+\-[0-9a-fA-F]+\b", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"%x[0-9a-fA-F]+(\.[0-9a-fA-F]+)*\b", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b[0-9]+\*[0-9]+", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b[0-9]+\*", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b[0-9]+", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\*", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(ALPHA|BIT|C(?:HAR|R(?:(?:LF)?)|TL)|D(?:IGIT|QUOTE)|H(?:EXDIG|TAB)|L(?:F|WSP)|OCTET|SP|VCHAR|WSP)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z][a-zA-Z0-9-]*\b", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(=/|=|/)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\[\]()]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r".", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        AbnfLexer { inner }
    }
}

impl Lexer for AbnfLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
