// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: AntlrPythonLexer
// Root: PythonLexer, Language: AntlrLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::python::PythonLexer;
use crate::lexer::antlr::AntlrLexer;

/// Auto-generated AntlrPythonLexer lexer (DelegatingLexer).
pub struct AntlrPythonLexer {
    inner: DelegatingLexer,
}

impl AntlrPythonLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "ANTLR With Python Target",
                Box::new(PythonLexer::new()),
                Box::new(AntlrLexer::new()),
            ),
        }
    }
}

impl Lexer for AntlrPythonLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
