// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: AntlrRubyLexer
// Root: RubyLexer, Language: AntlrLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::ruby::RubyLexer;
use crate::lexer::antlr::AntlrLexer;

/// Auto-generated AntlrRubyLexer lexer (DelegatingLexer).
pub struct AntlrRubyLexer {
    inner: DelegatingLexer,
}

impl AntlrRubyLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "ANTLR With Ruby Target",
                Box::new(RubyLexer::new()),
                Box::new(AntlrLexer::new()),
            ),
        }
    }
}

impl Lexer for AntlrRubyLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
