// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: AntlrActionScriptLexer
// Root: ActionScriptLexer, Language: AntlrLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::actionscript::ActionScriptLexer;
use crate::lexer::antlr::AntlrLexer;

/// Auto-generated AntlrActionScriptLexer lexer (DelegatingLexer).
pub struct AntlrActionScriptLexer {
    inner: DelegatingLexer,
}

impl AntlrActionScriptLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "ANTLR With ActionScript Target",
                Box::new(ActionScriptLexer::new()),
                Box::new(AntlrLexer::new()),
            ),
        }
    }
}

impl Lexer for AntlrActionScriptLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
