// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: ArrowLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated ArrowLexer lexer.
pub struct ArrowLexer {
    inner: RegexLexer,
}

impl ArrowLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Arrow");
        inner.aliases = vec![
            "arrow",
        ];
        inner.filenames = vec![
            "*.arw",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^[|\s]+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        // State: blocks
        inner.states.insert("blocks".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"/-->$|\\-->$|/--<|\\--<|\^", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: statements
        inner.states.insert("statements".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("index".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"=", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"require|main", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"print", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::Push("print".to_string()) },
        ]);

        // State: expressions
        inner.states.insert("expressions".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[0-9]+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"true|false", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_CHAR).unwrap(), action: LexerAction::Push("char".to_string()) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("array".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"==|!=|<|>|\+|-|\*|/|%", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"and|or|not|length", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) },
            LexerRule { pattern: TokenPattern::new(r"([a-zA-Z_][a-zA-Z0-9_]*)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("index".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("expressions".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: print
        inner.states.insert("print".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: fparams
        inner.states.insert("fparams".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: escape
        inner.states.insert("escape".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"\\(["\\/abfnrtv]|[0-9]{1,3}|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: char
        inner.states.insert("char".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_CHAR).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^'\\]", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"[^"\\]+"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
        ]);

        // State: array
        inner.states.insert("array".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: fargs
        inner.states.insert("fargs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: index
        inner.states.insert("index".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        ArrowLexer { inner }
    }
}

impl Lexer for ArrowLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
