// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: ArturoLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated ArturoLexer lexer.
pub struct ArturoLexer {
    inner: RegexLexer,
}

impl ArturoLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Arturo");
        inner.aliases = vec![
            "arturo",
            "art",
        ];
        inner.filenames = vec![
            "*.art",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r";.*?$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^((\s#!)|(#!)).*?$", Token::COMMENT_HASHBANG).unwrap(), action: LexerAction::token(Token::COMMENT_HASHBANG) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"((?:fals|mayb|tru)e)\b", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(init|this)\b\??:?", Token::NAME_BUILTIN_PSEUDO).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"`.`", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\\\w+\b\??:?", Token::NAME_PROPERTY).unwrap(), action: LexerAction::token(Token::NAME_PROPERTY) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#\w+", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b[0-9]+\.[0-9]+", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b[0-9]+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\w+\b\??:", Token::NAME_LABEL).unwrap(), action: LexerAction::token(Token::NAME_LABEL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\'(?:\w+\b\??:?)", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\:\w+", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.\w+\??:?", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("inside-simple-string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"»", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("inside-smart-string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"«««", Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("inside-safe-string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{\/", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("inside-regex-string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{\:", Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("inside-curly-verb-string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("inside-curly-string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\-{3,}", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("inside-eof-string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[()[\],]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(!!|\->|\./|::|==>|[!#$&@|])", Token::NAME_DECORATOR).unwrap(), action: LexerAction::token(Token::NAME_DECORATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(\-(?:\->|:)|\.\.|//|:(?:[\-<>])|<(?:\-(?:(?:(?:\-)?)>)|(?:<=(?:(?:(?:=)?)>)|=(?:(?:=)?))>|[:>\\])|=(?:=>|>>|\|)|>:|\|=|[%*+\-./<=>\\\^_~ø∞])", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b\w+", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r".+$", Token::ERROR).unwrap(), action: LexerAction::token(Token::ERROR) });

        inner.states.insert("root".to_string(), root_rules);

        // State: inside-interpol
        inner.states.insert("inside-interpol".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: inside-template
        inner.states.insert("inside-template".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|\|\>", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string-escape
        inner.states.insert("string-escape".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"(\\(?:["\\nt]))"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: inside-simple-string
        inner.states.insert("inside-simple-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-interpol".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\<\|\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-template".to_string()) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"[^|"]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: inside-smart-string
        inner.states.insert("inside-smart-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-interpol".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\<\|\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-template".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^|\n]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: inside-safe-string
        inner.states.insert("inside-safe-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-interpol".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\<\|\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-template".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"»»»", Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^|»]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: inside-regex-string
        inner.states.insert("inside-regex-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[sSwWdDbBZApPxucItnvfr0]+", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-interpol".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\<\|\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-template".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\/\}", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^|\/]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        // State: inside-curly-verb-string
        inner.states.insert("inside-curly-verb-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-interpol".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\<\|\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-template".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\:\}", Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^|<:]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: inside-curly-string
        inner.states.insert("inside-curly-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-interpol".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\<\|\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-template".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^|<}]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: inside-eof-string
        inner.states.insert("inside-eof-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-interpol".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\<\|\|", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("inside-template".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\Z", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^|<]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: builtin-functions
        inner.states.insert("builtin-functions".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b(a(?:ll|n(?:[dy])|scii|ttr(?:(?:ibute(?:(?:Label)?))?))|b(?:inary|lockchar)|contains|d(?:at(?:(?:(?:abas)?)e)|ictionary)|e(?:mpty|qual|ve(?:n|ry)|xists)|f(?:alse|(?:loati|unctio)n)|greater(?:(?:OrEqual)?)|i(?:n(?:line|teger)|[fns])|key|l(?:abel|e(?:ap|ss(?:(?:OrEqual)?))|iteral|o(?:gical|wer))|n(?:and|egative|o(?:tEqual|[rt])|u(?:ll|meric))|o(?:dd|r)|p(?:ath(?:(?:Label)?)|ositive|r(?:efix|ime))|s(?:et|o(?:me|rted)|t(?:andalone|ring)|u(?:bset|ffix|perset))|t(?:r(?:ue|y)|ype)|u(?:nless|pper)|w(?:h(?:en|itespace)|ord)|x(?:(?:(?:n)?)or)|ymbol|zero)\b\?", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"\b(a(?:bs|c(?:os(?:(?:h)?)|sec(?:(?:h)?)|tan(?:(?:h)?))|dd|fter|lphabet|n(?:d|gle)|ppend|r(?:g(?:(?:s)?)|(?:it|ra)y)|s(?:(?:ec(?:(?:h)?)|in(?:(?:h)?))?)|t(?:an(?:(?:[2h])?)|tr(?:(?:s)?))|verage)|b(?:e(?:fore|nchmark)|lend|reak|uiltins(?:[12]))|c(?:a(?:ll|(?:pitaliz|s)e)|eil|h(?:op|unk)|l(?:ear|ose|uster)|o(?:lor|mbine|n(?:j|tinue)|py|s(?:(?:h)?)|uple)|sec(?:(?:h)?)|tan(?:(?:h)?)|ursor)|d(?:arken|e(?:c(?:(?:o(?:(?:d|upl)e))?)|fine|lete|saturate|viation)|i(?:ctionary|fference|g(?:est|its)|v)|o(?:(?:wnload)?)|(?:ro|u)p)|e(?:(?:lse|mpty|n(?:code|sure|v)|psilon|scape|x(?:ecute|it|p|t(?:end|ract)))?)|f(?:a(?:ctors|lse)|div|i(?:lter|rst)|l(?:atten|oor)|old|rom|unction)|g(?:amma|cd|et|oto)|h(?:ash|elp|ypot)|i(?:n(?:c|de(?:nt|x)|f(?:inity|o)|put|s(?:(?:er|pec)t)|tersection|vert)|[fn])|join|k(?:(?:ey|urtosi)s)|l(?:ast|e(?:t|venshtein)|i(?:ghten|st)|n|o(?:g|op|wer))|m(?:a(?:il|tch|ybe|[px])|edian|in|od(?:(?:ule)?)|ul)|n(?:and|e(?:[gw])|o(?:rmalize|[rtw])|ull)|o(?:pen|r|utdent)|p(?:a(?:d|nic|th|use)|erm(?:issions|utate)|i|o(?:w(?:erset|mod)|[pw])|r(?:efix|int(?:(?:s)?)|o(?:cess|duct)))|query|r(?:an(?:dom|ge)|e(?:ad|lative|move|n(?:ame|der)|p(?:eat|lace)|quest|turn|verse)|ound)|s(?:a(?:(?:mpl|turat)e)|cript|e(?:ch|lect|rve|[ct])|h(?:uffle|[lr])|i(?:n(?:(?:h)?)|ze)|kewness|lice|ort|plit|q(?:rt|ueeze)|t(?:ack|rip)|u(?:ffix|[bm])|witch|y(?:m(?:bols|link)|s))|t(?:a(?:ke|n(?:(?:h)?))|erminal|o|r(?:u(?:(?:(?:ncat)?)e)|y)|ype)|u(?:n(?:i(?:on|que)|less|til|zip)|pper)|v(?:a(?:lues|r(?:(?:iance)?))|olume)|w(?:ebview|hile|ith|ordwrap|rite)|x(?:(?:(?:n)?)or)|zip)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
        ]);

        ArturoLexer { inner }
    }
}

impl Lexer for ArturoLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
