// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: BatchLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated BatchLexer lexer.
pub struct BatchLexer {
    inner: RegexLexer,
}

impl BatchLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Batchfile");
        inner.aliases = vec![
            "batch",
            "bat",
            "dosbatch",
            "winbatch",
        ];
        inner.filenames = vec![
            "*.bat",
            "*.cmd",
        ];
        inner.mimetypes = vec![
            "application/x-dos-batch",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\)((?=\()|(?=\^?[\t\v\f\r ,;=\xa0]|[&<>|\n\x1a]))(?:(?:[^\n\x1a^]|\^[\n\x1a]?[\w\W])*)", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?=((?:(?<=^[^:])|^[^:]?)[\t\v\f\r ,;=\xa0]*)(:))", Token::TEXT).unwrap(), action: LexerAction::Push("follow".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\n\x1a]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root/compound".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(assoc|break|c(?:d|hdir|ls|o(?:lor|py))|d(?:ate|el|ir|path)|e(?:cho|ndlocal|rase|xit)|ftype|keys|m(?:d|k(?:dir|link)|ove)|p(?:a(?:th|use)|opd|rompt|ushd)|r(?:d|en(?:(?:ame)?)|mdir)|s(?:etlocal|(?:hif|tar)t)|t(?:(?:i(?:m|tl)|yp)e)|v(?:er(?:(?:ify)?)|ol))(?=(?:\^[\n\x1a]?)?[\t\v\f\r ,;=\xa0+./:[\\\]]|[\n\x1a&<>|(])", Token::KEYWORD).unwrap(), action: LexerAction::Push("follow".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"call(?=(?:\^[\n\x1a]?)?[\t\v\f\r ,;=\xa0+./:[\\\]]|[\n\x1a&<>|(])", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"for(?=\^?[\t\v\f\r ,;=\xa0]|[&<>|\n\x1a])(?!\^)", Token::KEYWORD).unwrap(), action: LexerAction::Push("for2".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r#"rem(((?=\()|(?=\^?[\t\v\f\r ,;=\xa0]|[&<>|\n\x1a]))(?:(?:(?:\^[\n\x1a])?[\t\v\f\r ,;=\xa0])+)?(?:[&<>|]+|(?:(?:"[^\n\x1a"]*(?:"|(?=[\n\x1a])))|(?:(?:%(?:\*|(?:~[a-z]*(?:\$[^:]+:)?)?\d|[^%:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^%\n\x1a^]|\^[^%\n\x1a])[^=\n\x1a]*=(?:[^%\n\x1a^]|\^[^%\n\x1a])*)?)?%))|(?:\^?![^!:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^!\n\x1a^]|\^[^!\n\x1a])[^=\n\x1a]*=(?:[^!\n\x1a^]|\^[^!\n\x1a])*)?)?\^?!))|(?:(?:(?:\^[\n\x1a]?)?[^"\s\x1a\xa0,;=&<>|])+))+)?.*|(?=(?:\^[\n\x1a]?)?[\t\v\f\r ,;=\xa0+./:[\\\]]|[\n\x1a&<>|(])(?:(?:[^\n\x1a^]|\^[\n\x1a]?[\w\W])*))"#, Token::COMMENT_SINGLE).unwrap(), action: LexerAction::Push("follow".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        // State: follow
        inner.states.insert("follow".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?=[\n\x1a])", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\|\|?|&&?", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: arithmetic
        inner.states.insert("arithmetic".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"0[0-7]+", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"0x[\da-f]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"[(),]+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"([=+\-*/!~]|%|\^\^)+", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"(?=[\x00|&])", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: call
        inner.states.insert("call".to_string(), vec![
        ]);

        // State: label
        inner.states.insert("label".to_string(), vec![
        ]);

        // State: redirect
        inner.states.insert("redirect".to_string(), vec![
        ]);

        // State: root/compound
        inner.states.insert("root/compound".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?=((?:(?<=^[^:])|^[^:]?)[\t\v\f\r ,;=\xa0]*)(:))", Token::TEXT).unwrap(), action: LexerAction::Push("follow/compound".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[\n\x1a]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root/compound".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"@+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"(assoc|break|c(?:d|hdir|ls|o(?:lor|py))|d(?:ate|el|ir|path)|e(?:cho|ndlocal|rase|xit)|ftype|keys|m(?:d|k(?:dir|link)|ove)|p(?:a(?:th|use)|opd|rompt|ushd)|r(?:d|en(?:(?:ame)?)|mdir)|s(?:etlocal|(?:hif|tar)t)|t(?:(?:i(?:m|tl)|yp)e)|v(?:er(?:(?:ify)?)|ol))(?:(?=\))|(?=(?:\^[\n\x1a]?)?[\t\v\f\r ,;=\xa0+./:[\\\]]|[\n\x1a&<>|(]))", Token::KEYWORD).unwrap(), action: LexerAction::Push("follow/compound".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"call(?:(?=\))|(?=(?:\^[\n\x1a]?)?[\t\v\f\r ,;=\xa0+./:[\\\]]|[\n\x1a&<>|(]))", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"for(?:(?=\))|(?=\^?[\t\v\f\r ,;=\xa0]|[&<>|\n\x1a]))(?!\^)", Token::KEYWORD).unwrap(), action: LexerAction::Push("for2".to_string()) },
            LexerRule { pattern: TokenPattern::new(r#"rem(((?=\()|(?:(?=\))|(?=\^?[\t\v\f\r ,;=\xa0]|[&<>|\n\x1a])))(?:(?:(?:\^[\n\x1a])?[\t\v\f\r ,;=\xa0])+)?(?:[&<>|]+|(?:(?:"[^\n\x1a"]*(?:"|(?=[\n\x1a])))|(?:(?:%(?:\*|(?:~[a-z]*(?:\$[^:]+:)?)?\d|[^%:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^%\n\x1a^]|\^[^%\n\x1a])[^=\n\x1a]*=(?:[^%\n\x1a^]|\^[^%\n\x1a])*)?)?%))|(?:\^?![^!:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^!\n\x1a^]|\^[^!\n\x1a])[^=\n\x1a]*=(?:[^!\n\x1a^]|\^[^!\n\x1a])*)?)?\^?!))|(?:(?:(?:\^[\n\x1a]?)?[^"\s\x1a\xa0,;=&<>|])+))+)?.*|(?:(?=\))|(?=(?:\^[\n\x1a]?)?[\t\v\f\r ,;=\xa0+./:[\\\]]|[\n\x1a&<>|(]))(?:(?:[^\n\x1a^)]|\^[\n\x1a]?[^)])*))"#, Token::COMMENT_SINGLE).unwrap(), action: LexerAction::Push("follow/compound".to_string()) },
        ]);

        // State: follow/compound
        inner.states.insert("follow/compound".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?=\))", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?=[\n\x1a])", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\|\|?|&&?", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: arithmetic/compound
        inner.states.insert("arithmetic/compound".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?=\))", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"0[0-7]+", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"0x[\da-f]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"[(),]+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"([=+\-*/!~]|%|\^\^)+", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"(?=[\x00|&])", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: call/compound
        inner.states.insert("call/compound".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?=\))", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: label/compound
        inner.states.insert("label/compound".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?=\))", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: redirect/compound
        inner.states.insert("redirect/compound".to_string(), vec![
        ]);

        // State: variable-or-escape
        inner.states.insert("variable-or-escape".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?:(?:%(?:\*|(?:~[a-z]*(?:\$[^:]+:)?)?\d|[^%:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^%\n\x1a^]|\^[^%\n\x1a])[^=\n\x1a]*=(?:[^%\n\x1a^]|\^[^%\n\x1a])*)?)?%))|(?:\^?![^!:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^!\n\x1a^]|\^[^!\n\x1a])[^=\n\x1a]*=(?:[^!\n\x1a^]|\^[^!\n\x1a])*)?)?\^?!))", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"%%|\^[\n\x1a]?(\^!|[\w\W])", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?:(?:%(?:\*|(?:~[a-z]*(?:\$[^:]+:)?)?\d|[^%:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^%\n\x1a^]|\^[^%\n\x1a])[^=\n\x1a]*=(?:[^%\n\x1a^]|\^[^%\n\x1a])*)?)?%))|(?:\^?![^!:\n\x1a]+(?::(?:~(?:-?\d+)?(?:,(?:-?\d+)?)?|(?:[^!\n\x1a^]|\^[^!\n\x1a])[^=\n\x1a]*=(?:[^!\n\x1a^]|\^[^!\n\x1a])*)?)?\^?!))", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\^!|%%", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r#"[^"%^\n\x1a]+|[%^]"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
        ]);

        // State: sqstring
        inner.states.insert("sqstring".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^%]+|%", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
        ]);

        // State: bqstring
        inner.states.insert("bqstring".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^%]+|%", Token::STRING_BACKTICK).unwrap(), action: LexerAction::token(Token::STRING_BACKTICK) },
        ]);

        // State: text
        inner.states.insert("text".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r#"[^"%^\s\x1a\xa0,;=&<>|\d)]+|."#, Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        // State: variable
        inner.states.insert("variable".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r#"[^"%^\n\x1a]+|."#, Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
        ]);

        // State: for
        inner.states.insert("for".to_string(), vec![
        ]);

        // State: for2
        inner.states.insert("for2".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[\n\x1a]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        // State: for/f
        inner.states.insert("for/f".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: for/l
        inner.states.insert("for/l".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"-?\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
        ]);

        // State: if
        inner.states.insert("if".to_string(), vec![
        ]);

        // State: if2
        inner.states.insert("if2".to_string(), vec![
        ]);

        // State: (?
        inner.states.insert("(?".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: else?
        inner.states.insert("else?".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"else(?=\^?[\t\v\f\r ,;=\xa0]|[&<>|\n\x1a])", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        BatchLexer { inner }
    }
}

impl Lexer for BatchLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
