// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: BCLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated BCLexer lexer.
pub struct BCLexer {
    inner: RegexLexer,
}

impl BCLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("BC");
        inner.aliases = vec![
            "bc",
        ];
        inner.filenames = vec![
            "*.bc",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\*", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("comment".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(?:[^"\\]|\\.)*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[{}();,]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(auto|break|continue|define|else|for|halt|if|l(?:ength|imits)|print|quit|re(?:ad|turn)|s(?:cale|qrt)|w(?:arranty|hile))\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\+\+|--|\|\||&&|([-<>+*%\^/!=])=?", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+(\.[0-9]*)?", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.[0-9]+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r".", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: comment
        inner.states.insert("comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^*/]+", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"\*/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[*/]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        BCLexer { inner }
    }
}

impl Lexer for BCLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
