// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: BddLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated BddLexer lexer.
pub struct BddLexer {
    inner: RegexLexer,
}

impl BddLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Bdd");
        inner.aliases = vec![
            "bdd",
        ];
        inner.filenames = vec![
            "*.feature",
        ];
        inner.mimetypes = vec![
            "text/x-bdd",
        ];

        // State: comments
        inner.states.insert("comments".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"^\s*#.*$", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        // State: miscellaneous
        inner.states.insert("miscellaneous".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(<|>|\[|\]|=|\||:|\(|\)|\{|\}|,|\.|;|-|_|\$)", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"((?<=\<)[^\\>]+(?=\>))", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r##""([^\"]*)""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"^@\S+", Token::NAME_LABEL).unwrap(), action: LexerAction::token(Token::NAME_LABEL) },
        ]);

        // State: numbers
        inner.states.insert("numbers".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(\d+\.?\d*|\d*\.\d+)([eE][+-]?[0-9]+)?", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"Given|When|Then|Add|And|Feature|Scenario Outline|Scenario|Background|Examples|But", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\S+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        BddLexer { inner }
    }
}

impl Lexer for BddLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
