// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: BibTeXLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated BibTeXLexer lexer.
pub struct BibTeXLexer {
    inner: RegexLexer,
}

impl BibTeXLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("BibTeX");
        inner.aliases = vec![
            "bibtex",
            "bib",
        ];
        inner.filenames = vec![
            "*.bib",
        ];
        inner.mimetypes = vec![
            "text/x-bibtex",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@comment(?!ary)", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@preamble", Token::NAME_CLASS).unwrap(), action: LexerAction::Push("closing-brace".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@string", Token::NAME_CLASS).unwrap(), action: LexerAction::Push("closing-brace".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@[a-z_@!$&*+\-./:;<>?\[\\\]^`|~][\w@!$&*+\-./:;<>?\[\\\]^`|~]*", Token::NAME_CLASS).unwrap(), action: LexerAction::Push("closing-brace".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r".+", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: opening-brace
        inner.states.insert("opening-brace".to_string(), vec![
        ]);

        // State: closing-brace
        inner.states.insert("closing-brace".to_string(), vec![
        ]);

        // State: command-body
        inner.states.insert("command-body".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^\s\,\}]+", Token::NAME_LABEL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: fields
        inner.states.insert("fields".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("field".to_string()) },
        ]);

        // State: field
        inner.states.insert("field".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-z_@!$&*+\-./:;<>?\[\\\]^`|~][\w@!$&*+\-./:;<>?\[\\\]^`|~]*", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::Push("value".to_string()) },
        ]);

        // State: =
        inner.states.insert("=".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"=", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: value
        inner.states.insert("value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-z_@!$&*+\-./:;<>?\[\\\]^`|~][\w@!$&*+\-./:;<>?\[\\\]^`|~]*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::Push("quoted-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING).unwrap(), action: LexerAction::Push("braced-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[\d]+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: quoted-string
        inner.states.insert("quoted-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING).unwrap(), action: LexerAction::Push("braced-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"[^\{\"]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: braced-string
        inner.states.insert("braced-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^\{\}]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
        ]);

        BibTeXLexer { inner }
    }
}

impl Lexer for BibTeXLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
