// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: BQNLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated BQNLexer lexer.
pub struct BQNLexer {
    inner: RegexLexer,
}

impl BQNLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("BQN");
        inner.aliases = vec![
            "bqn",
        ];
        inner.filenames = vec![
            "*.bqn",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#.*$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\'((\'\')|[^\'])*\'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(("")|[^"])*""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\.⋄,\[\]⟨⟩‿]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\(\)]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"¯?[0-9](([0-9]|_)*\.?([0-9]|_)+|([0-9]|_)*)([Ee][¯]?([0-9]|_)+)?|¯|∞|π|·", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-z]((?=[^𝕎𝕏𝔽𝔾𝕊𝕨𝕩𝕗𝕘𝕤𝕣])\w)*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[∘○⊸⟜⌾⊘◶⎉⚇⍟⎊]", Token::NAME_PROPERTY).unwrap(), action: LexerAction::token(Token::NAME_PROPERTY) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"_(𝕣|[a-zA-Z0-9]+)_", Token::NAME_PROPERTY).unwrap(), action: LexerAction::token(Token::NAME_PROPERTY) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[˙˜˘¨⌜⁼´˝`𝕣]", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"_(𝕣|[a-zA-Z0-9]+)", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[+\-×÷\⋆√⌊⌈∧∨¬|≤<>≥=≠≡≢⊣⊢⥊∾≍⋈↑↓↕«»⌽⍉/⍋⍒⊏⊑⊐⊒∊⍷⊔!𝕎𝕏𝔽𝔾𝕊]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[A-Z]((?=[^𝕎𝕏𝔽𝔾𝕊𝕨𝕩𝕗𝕘𝕤𝕣])\w)*|•((?=[^𝕎𝕏𝔽𝔾𝕊𝕨𝕩𝕗𝕘𝕤𝕣])\w)+", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"˙", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[←↩⇐]", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[{}]", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[;:?𝕨𝕩𝕗𝕘𝕤]", Token::NAME_ENTITY).unwrap(), action: LexerAction::token(Token::NAME_ENTITY) });

        inner.states.insert("root".to_string(), root_rules);

        BQNLexer { inner }
    }
}

impl Lexer for BQNLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
