// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: CadlLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated CadlLexer lexer.
pub struct CadlLexer {
    inner: RegexLexer,
}

impl CadlLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("cADL");
        inner.aliases = vec![
            "cadl",
        ];
        inner.filenames = vec![
            "*.cadl",
        ];

        // State: path
        inner.states.insert("path".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
            LexerRule { pattern: TokenPattern::new(r"/", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("any_code".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(cardinality|existence|occurrences|group|include|exclude|allow_archetype|use_archetype|use_node)\W", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(and|or|not|there_exists|xor|implies|for_all)\W", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(after|before|closed)\W", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(not)\W", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(matches|is_in)\W", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(∈|∉)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(∃|∄|∀|∧|∨|⊻|C)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("path".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\[\{", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\}\]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[A-Z]\w+(<[A-Z]\w+([A-Za-z_<>]*)>)?", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("any_code".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(~|//|\\\\|\+|-|/|\*|\^|!=|=|<=|>=|<|>]?)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::Push("string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
        ]);

        // State: archetype_id
        inner.states.insert("archetype_id".to_string(), vec![
        ]);

        // State: date_constraints
        inner.states.insert("date_constraints".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[Xx?YyMmDdHhSs\d]{2,4}([:-][Xx?YyMmDdHhSs\d]{2}){2}", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
            LexerRule { pattern: TokenPattern::new(r"(P[YyMmWwDd]+(T[HhMmSs]+)?|PT[HhMmSs]+)/?", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
        ]);

        // State: ordered_values
        inner.states.insert("ordered_values".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\d{4}-\d{2}-\d{2}T?", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
            LexerRule { pattern: TokenPattern::new(r"\d{2}:\d{2}:\d{2}(\.\d+)?([+-]\d{4}|Z)?", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
            LexerRule { pattern: TokenPattern::new(r"P((\d*(\.\d+)?[YyMmWwDd]){1,3}(T(\d*(\.\d+)?[HhMmSs]){,3})?|T(\d*(\.\d+)?[HhMmSs]){,3})", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
            LexerRule { pattern: TokenPattern::new(r"[+-]?(\d+\.\d*|\.\d+|\d+)[eE][+-]?\d+", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"[+-]?\d*\.\d+%?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"[+-]?\d+%?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
        ]);

        // State: values
        inner.states.insert("values".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([Tt]rue|[Ff]alse)", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"'(\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) },
            LexerRule { pattern: TokenPattern::new(r"[a-z][a-z0-9+.-]*:", Token::LITERAL).unwrap(), action: LexerAction::Push("uri".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\|", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("interval".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\.\.\.", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: constraint_values
        inner.states.insert("constraint_values".to_string(), vec![
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"\\([\\abfnrtv"\']|x[a-fA-F0-9]{2,4}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|[0-7]{1,3})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\"]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\\", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: uri
        inner.states.insert("uri".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[,>\s]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^>\s,]+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
        ]);

        // State: interval
        inner.states.insert("interval".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\.\.", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[<>=] *", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\+/-", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: any_code
        inner.states.insert("any_code".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-z_]\w*[0-9.]+(@[^\]]+)?", Token::NAME_DECORATOR).unwrap(), action: LexerAction::token(Token::NAME_DECORATOR) },
            LexerRule { pattern: TokenPattern::new(r"[a-z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
            LexerRule { pattern: TokenPattern::new(r"[0-9]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"\|", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("code_rubric".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: code_rubric
        inner.states.insert("code_rubric".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\|", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^|]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: adl14_code_constraint
        inner.states.insert("adl14_code_constraint".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\|", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("code_rubric".to_string()) },
        ]);

        CadlLexer { inner }
    }
}

impl Lexer for CadlLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
