// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: CAmkESLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated CAmkESLexer lexer.
pub struct CAmkESLexer {
    inner: RegexLexer,
}

impl CAmkESLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("CAmkES");
        inner.aliases = vec![
            "camkes",
            "idl4",
        ];
        inner.filenames = vec![
            "*.camkes",
            "*.idl4",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\*(.|\n)*?\*/", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"//.*$", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\[(){},.;\]]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[~!%^&*+=|?:<>/-]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(Dataport(?:(?:s)?)|Event(?:(?:s)?)|Interface|Procedure(?:(?:s)?)|a(?:ssembly|ttribute)|co(?:mpo(?:nent|sition)|n(?:figuration|nect(?:ion|or)|sumes|trol))|dataport|e(?:mits|(?:ven|xpor)t)|from|group|ha(?:rdware|s)|interface|maybe|pro(?:cedure|vides)|t(?:emplate|hread(?:(?:s)?)|o)|uses|with)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(Buf|bool(?:(?:ean)?)|char(?:(?:acter)?)|double|float|in(?:(?:out|t(?:(?:16_6|32_t|64_t|8_t|eger)?))?)|mutex|out|re(?:al|fin)|s(?:emaphore|igned|tr(?:ing|uct))|u(?:int(?:(?:16|32|64|8|ptr)_t)|nsigned)|void)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*_(priority|domain|buffer)", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(dma_pool|(?:from|to)_access)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[xX][\da-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?[\d]+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?[\d]+\.[\d]+", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""[^"]*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[Tt]rue|[Ff]alse", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });

        inner.states.insert("root".to_string(), root_rules);

        CAmkESLexer { inner }
    }
}

impl Lexer for CAmkESLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
