// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: CapnProtoLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated CapnProtoLexer lexer.
pub struct CapnProtoLexer {
    inner: RegexLexer,
}

impl CapnProtoLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Cap'n Proto");
        inner.aliases = vec![
            "capnp",
        ];
        inner.filenames = vec![
            "*.capnp",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#.*?$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@[0-9a-zA-Z]*", Token::NAME_DECORATOR).unwrap(), action: LexerAction::token(Token::NAME_DECORATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"=", Token::LITERAL).unwrap(), action: LexerAction::Push("expression".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r":", Token::NAME_CLASS).unwrap(), action: LexerAction::Push("type".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\$", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::Push("annotation".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(struct|enum|interface|union|import|using|const|annotation|extends|in|of|on|as|with|from|fixed)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\w.]+", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[^#@=:$\w\s]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: type
        inner.states.insert("type".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^][=;,(){}$]+", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
            LexerRule { pattern: TokenPattern::new(r"[\[(]", Token::NAME_CLASS).unwrap(), action: LexerAction::Push("parentype".to_string()) },
        ]);

        // State: parentype
        inner.states.insert("parentype".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^][;()]+", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
            LexerRule { pattern: TokenPattern::new(r"[\[(]", Token::NAME_CLASS).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[])]", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: expression
        inner.states.insert("expression".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^][;,(){}$]+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
            LexerRule { pattern: TokenPattern::new(r"[\[(]", Token::LITERAL).unwrap(), action: LexerAction::Push("parenexp".to_string()) },
        ]);

        // State: parenexp
        inner.states.insert("parenexp".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^][;()]+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
            LexerRule { pattern: TokenPattern::new(r"[\[(]", Token::LITERAL).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[])]", Token::LITERAL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: annotation
        inner.states.insert("annotation".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^][;,(){}=:]+", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) },
            LexerRule { pattern: TokenPattern::new(r"[\[(]", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::Push("annexp".to_string()) },
        ]);

        // State: annexp
        inner.states.insert("annexp".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^][;()]+", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) },
            LexerRule { pattern: TokenPattern::new(r"[\[(]", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[])]", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        CapnProtoLexer { inner }
    }
}

impl Lexer for CapnProtoLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
