// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: CeylonLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated CeylonLexer lexer.
pub struct CeylonLexer {
    inner: RegexLexer,
}

impl CeylonLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Ceylon");
        inner.aliases = vec![
            "ceylon",
        ];
        inner.filenames = vec![
            "*.ceylon",
        ];
        inner.mimetypes = vec![
            "text/x-ceylon",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\*", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("comment".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(shared|abstract|formal|default|actual|variable|deprecated|small|late|literal|doc|by|see|throws|optional|license|tagged|final|native|annotation|sealed)\b", Token::NAME_DECORATOR).unwrap(), action: LexerAction::token(Token::NAME_DECORATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(break|case|catch|continue|else|finally|for|in|if|return|switch|this|throw|try|while|is|exists|dynamic|nonempty|then|outer|assert|let)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(abstracts|extends|satisfies|super|given|of|out|assign)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(function|value|void|new)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(true|false|null)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'\\.'|'[^\\]'|'\\\{#[0-9a-fA-F]{4}\}'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*:", Token::NAME_LABEL).unwrap(), action: LexerAction::token(Token::NAME_LABEL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[~^*!%&\[\](){}<>|+=:;,./?-]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d{1,3}(_\d{3})+\.\d{1,3}(_\d{3})+[kMGTPmunpf]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d{1,3}(_\d{3})+\.[0-9]+([eE][+-]?[0-9]+)?[kMGTPmunpf]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9][0-9]*\.\d{1,3}(_\d{3})+[kMGTPmunpf]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9][0-9]*\.[0-9]+([eE][+-]?[0-9]+)?[kMGTPmunpf]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#([0-9a-fA-F]{4})(_[0-9a-fA-F]{4})+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\$([01]{4})(_[01]{4})+", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\$[01]+", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d{1,3}(_\d{3})+[kMGTP]?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+[kMGTP]?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });

        inner.states.insert("root".to_string(), root_rules);

        // State: class
        inner.states.insert("class".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[A-Za-z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: import
        inner.states.insert("import".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-z][\w.]*", Token::NAME_NAMESPACE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: comment
        inner.states.insert("comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^*/]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/\*", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\*/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[*/]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        CeylonLexer { inner }
    }
}

impl Lexer for CeylonLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
