// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: ChapelLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated ChapelLexer lexer.
pub struct ChapelLexer {
    inner: RegexLexer,
}

impl ChapelLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Chapel");
        inner.aliases = vec![
            "chapel",
            "chpl",
        ];
        inner.filenames = vec![
            "*.chpl",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\\\n", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"//(.*?)\n", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*](.|\n)*?[*](\\\n)?/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(con(?:fig|st)|in(?:(?:out)?)|out|param|ref|type|var)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(false|n(?:il|one)|true)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(b(?:ool|ytes)|complex|i(?:mag|nt)|locale|nothing|opaque|r(?:ange|eal)|string|uint|void)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(a(?:lign|s|tomic)|b(?:egin|orrowed|reak|y)|c(?:atch|o(?:begin|forall|ntinue))|d(?:e(?:fer|lete)|mapped|o(?:(?:main)?))|e(?:lse|num|x(?:cept|port|tern))|for(?:(?:all|each|warding)?)|i(?:f|mp(?:lements|ort)|n(?:dex|it|line))|l(?:a(?:bel|mbda)|et|ifetime|ocal)|n(?:ew|oinit)|o(?:n(?:(?:ly)?)|therwise|verride|wned)|p(?:r(?:agma|(?:i(?:mitiv|vat)|ototyp)e)|ublic)|re(?:duce|quire|turn)|s(?:can|e(?:lect|rial)|hared|ingle|parse|ubdomain|ync)|t(?:h(?:en|is|row(?:(?:s)?))|ry)|u(?:nmanaged|se)|w(?:h(?:e(?:n|re)|ile)|ith)|yield|zip)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@", Token::KEYWORD).unwrap(), action: LexerAction::Push("attributename".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d+i", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d+\.\d*([Ee][-+]\d+)?i", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.\d+([Ee][-+]\d+)?i", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d+[Ee][-+]\d+i", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(\d*\.\d+)([eE][+-]?[0-9]+)?i?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d+[eE][+-]?[0-9]+i?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[bB][01]+", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[xX][0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[oO][0-7]+", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(\\\\|\\"|[^"])*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'(\\\\|\\'|[^'])*'", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(=|\+=|-=|\*=|/=|\*\*=|%=|&=|\|=|\^=|&&=|\|\|=|<<=|>>=|<=>|<~>|\.\.|by|#|\.\.\.|&&|\|\||!|&|\||\^|~|<<|>>|==|!=|<=|>=|<|>|[+\-*/%]|\*\*)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[:;,.?()\[\]{}]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_][\w$]*", Token::NAME_OTHER).unwrap(), action: LexerAction::token(Token::NAME_OTHER) });

        inner.states.insert("root".to_string(), root_rules);

        // State: classname
        inner.states.insert("classname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_][\w$]*", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: procname
        inner.states.insert("procname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([a-zA-Z_][.\w$]*|\~[a-zA-Z_][.\w$]*|[+*/!~%<>=&^|\-:]{1,2})", Token::NAME_FUNCTION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("receivertype".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)+\.", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: receivertype
        inner.states.insert("receivertype".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(atomic|borrowed|owned|s(?:hared|ingle|ync)|unmanaged)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(b(?:ool|ytes)|complex|i(?:mag|nt)|locale|nothing|opaque|r(?:ange|eal)|string|uint|void)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"[^()]*", Token::NAME_OTHER).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: attributename
        inner.states.insert("attributename".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_][.\w$]*", Token::NAME_DECORATOR).unwrap(), action: LexerAction::PopN(1) },
        ]);

        ChapelLexer { inner }
    }
}

impl Lexer for ChapelLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
