// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: CMakeLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated CMakeLexer lexer.
pub struct CMakeLexer {
    inner: RegexLexer,
}

impl CMakeLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("CMake");
        inner.aliases = vec![
            "cmake",
        ];
        inner.filenames = vec![
            "*.cmake",
            "CMakeLists.txt",
        ];
        inner.mimetypes = vec![
            "text/x-cmake",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();


        inner.states.insert("root".to_string(), root_rules);

        // State: args
        inner.states.insert("args".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r##"".*?""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r"\\\S+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r#"[^)$"# \t\n]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: keywords
        inner.states.insert("keywords".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b(WIN32|UNIX|APPLE|CYGWIN|BORLAND|MINGW|MSVC|MSVC_IDE|MSVC60|MSVC70|MSVC71|MSVC80|MSVC90)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
        ]);

        // State: ws
        inner.states.insert("ws".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#\[(?:=*)\[[\w\W]*?\](?P=level)\]", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
            LexerRule { pattern: TokenPattern::new(r"#.*\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        CMakeLexer { inner }
    }
}

impl Lexer for CMakeLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
