// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: CObjdumpLexer
// Root: CLexer, Language: ObjdumpLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::cpp::CLexer;
use crate::lexer::objdump::ObjdumpLexer;

/// Auto-generated CObjdumpLexer lexer (DelegatingLexer).
pub struct CObjdumpLexer {
    inner: DelegatingLexer,
}

impl CObjdumpLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "c-objdump",
                Box::new(CLexer::new()),
                Box::new(ObjdumpLexer::new()),
            ),
        }
    }
}

impl Lexer for CObjdumpLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
