// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: CrystalLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated CrystalLexer lexer.
pub struct CrystalLexer {
    inner: RegexLexer,
}

impl CrystalLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Crystal");
        inner.aliases = vec![
            "cr",
            "crystal",
        ];
        inner.filenames = vec![
            "*.cr",
        ];
        inner.mimetypes = vec![
            "text/x-crystal",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#.*?$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(a(?:bstract|sm)|b(?:egin|reak)|case|do|e(?:ls(?:e|if)|n(?:d|sure)|xtend)|i(?:nclude|[fn])|next|of|pr(?:ivate|otected)|re(?:quire|scue|turn)|s(?:el(?:ect|f)|uper)|then|un(?:less|til)|w(?:h(?:en|ile)|ith)|yield)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<!\.)(__(?:(?:DIR|(?:END_LIN|FIL|LIN)E)__)|forall|out|previous_def|uninitialized)\b", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.(is_a\?|nil\?|responds_to\?|as\?|as\b)", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(false|nil|true)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"def(?=[*%&^`~+-/\[<>=])", Token::KEYWORD).unwrap(), action: LexerAction::Push("funcname".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<!\.)((?:instance_size|offset|pointer|(?:siz|typ)e)of)\b", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<!\.)(debugger\b|p!|pp!|record\b|spawn\b)", Token::NAME_BUILTIN_PSEUDO).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<!\.)(a(?:(?:bor|t_exi)t)|caller|exit|gets|loop|main|p(?:(?:p|rint(?:(?:f)?)|uts)?)|r(?:a(?:ise|nd)|ead_line)|s(?:leep|p(?:awn|rintf)|ystem))\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<!\.)(((class_)?((getter|property)\b[!?]?|setter\b))|(def_(clone|equals|equals_and_hash|hash)|delegate|forward_missing_to)\b)", Token::NAME_BUILTIN_PSEUDO).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"__END__", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("end-part".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<=\(|,|\[)/", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("multiline-regex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@@[a-zA-Z_]\w*", Token::NAME_VARIABLE_CLASS).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_CLASS) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@[a-zA-Z_]\w*", Token::NAME_VARIABLE_INSTANCE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_INSTANCE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\$\w+", Token::NAME_VARIABLE_GLOBAL).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_GLOBAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r#"\$[!@&`\'+~=/\\,;.<>_*$?:"^-]"#, Token::NAME_VARIABLE_GLOBAL).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_GLOBAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\$-[0adFiIlpvw]", Token::NAME_VARIABLE_GLOBAL).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_GLOBAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"::", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"\?(\\[MC]-)*(\\([\\abefnrtv#"\']|[0-7]{1,3}|x[a-fA-F0-9]{2}|u[a-fA-F0-9]{4}|u\{[a-fA-F0-9 ]+\})|\S)(?!\w)"##, Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[A-Z][A-Z_]+\b(?!::|\.)", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{%", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("in-macro-control".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("in-macro-expr".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*(?:[!?](?!=))?", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(\[|\]\??|\*\*|<=>?|>=|<<?|>>?|=~|===|!~|&&?|\|\||\.{1,3})", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[-+/*%=<>&!^|~]=?", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[(){};,/?:\\]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        // State: funcname
        inner.states.insert("funcname".to_string(), vec![
        ]);

        // State: classname
        inner.states.insert("classname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[A-Z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
        ]);

        // State: in-intp
        inner.states.insert("in-intp".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string-intp
        inner.states.insert("string-intp".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("in-intp".to_string()) },
        ]);

        // State: string-escaped
        inner.states.insert("string-escaped".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"\\([\\abefnrtv#"\']|[0-7]{1,3}|x[a-fA-F0-9]{2}|u[a-fA-F0-9]{4}|u\{[a-fA-F0-9 ]+\})"##, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: interpolated-regex
        inner.states.insert("interpolated-regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[\\#]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        // State: interpolated-string
        inner.states.insert("interpolated-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[\\#]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: multiline-regex
        inner.states.insert("multiline-regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\\\", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"\\/", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[\\#]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[^\\/#]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"/[imsx]*", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: end-part
        inner.states.insert("end-part".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r".+", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: in-macro-control
        inner.states.insert("in-macro-control".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\{%", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(for|verbatim)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
        ]);

        // State: in-macro-expr
        inner.states.insert("in-macro-expr".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\{\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: in-annot
        inner.states.insert("in-annot".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::OPERATOR).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::OPERATOR).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: strings
        inner.states.insert("strings".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\:\w+[!?]?", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r"\:(!(?:[=~])|\&\&|\*\*|<(?:=>|[<=])|=(?:==|[=~])|>(?:[=>])|\[\](?:(?:[=?])?)|\|\||[!%&*+\-/<=>\^|~])", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r":'(\\\\|\\[^\\]|[^'\\])*'", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r"'(\\\\|\\'|[^']|\\[^'\\]+)'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) },
            LexerRule { pattern: TokenPattern::new(r##":""##, Token::STRING_SYMBOL).unwrap(), action: LexerAction::Push("simple-sym".to_string()) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("simple-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(?<!\.)`", Token::STRING_BACKTICK).unwrap(), action: LexerAction::Push("simple-backtick".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%Q?\{", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("cb-intp-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%[qwi]\{", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("cb-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%r\{", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("cb-regex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%Q?\[", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("sb-intp-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%[qwi]\[", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("sb-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%r\[", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("sb-regex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%Q?\(", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("pa-intp-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%[qwi]\(", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("pa-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%r\(", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("pa-regex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%Q?<", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("ab-intp-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%[qwi]<", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("ab-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%r<", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("ab-regex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%Q?\|", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("pi-intp-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%[qwi]\|", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("pi-string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"%r\|", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("pi-regex".to_string()) },
        ]);

        // State: simple-string
        inner.states.insert("simple-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"[^\\"#]+"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r"[\\#]", Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: simple-sym
        inner.states.insert("simple-sym".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"[^\\"#]+"#, Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r"[\\#]", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_SYMBOL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: simple-backtick
        inner.states.insert("simple-backtick".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^\\`#]+", Token::STRING_BACKTICK).unwrap(), action: LexerAction::token(Token::STRING_BACKTICK) },
            LexerRule { pattern: TokenPattern::new(r"[\\#]", Token::STRING_BACKTICK).unwrap(), action: LexerAction::token(Token::STRING_BACKTICK) },
            LexerRule { pattern: TokenPattern::new(r"`", Token::STRING_BACKTICK).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: cb-intp-string
        inner.states.insert("cb-intp-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\\{", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#{}]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#{}]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: cb-string
        inner.states.insert("cb-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\{}]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#{}]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#{}]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: cb-regex
        inner.states.insert("cb-regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\{}]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}[imsx]*", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#{}]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#{}]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        // State: sb-intp-string
        inner.states.insert("sb-intp-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\\[", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#\[\]]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#\[\]]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: sb-string
        inner.states.insert("sb-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\\[\]]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#\[\]]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#\[\]]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: sb-regex
        inner.states.insert("sb-regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\\[\]]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\][imsx]*", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#\[\]]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#\[\]]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        // State: pa-intp-string
        inner.states.insert("pa-intp-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\\(", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#()]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#()]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: pa-string
        inner.states.insert("pa-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\()]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#()]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#()]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: pa-regex
        inner.states.insert("pa-regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\()]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)[imsx]*", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#()]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#()]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        // State: ab-intp-string
        inner.states.insert("ab-intp-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\<", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"<", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r">", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#<>]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#<>]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: ab-string
        inner.states.insert("ab-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\<>]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"<", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r">", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#<>]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#<>]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: ab-regex
        inner.states.insert("ab-regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\<>]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"<", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r">[imsx]*", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#<>]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#<>]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        // State: pi-intp-string
        inner.states.insert("pi-intp-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\\|", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#\|]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#\|]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: pi-string
        inner.states.insert("pi-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\\|]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\|", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#\|]", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#\|]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: pi-regex
        inner.states.insert("pi-regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\[\\\|]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"\|[imsx]*", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\\#\|]", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
            LexerRule { pattern: TokenPattern::new(r"[^\\#\|]+", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        CrystalLexer { inner }
    }
}

impl Lexer for CrystalLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
