// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: CssDjangoLexer
// Root: CssLexer, Language: DjangoLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::css::CssLexer;
use crate::lexer::django::DjangoLexer;

/// Auto-generated CssDjangoLexer lexer (DelegatingLexer).
pub struct CssDjangoLexer {
    inner: DelegatingLexer,
}

impl CssDjangoLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "CSS+Django/Jinja",
                Box::new(CssLexer::new()),
                Box::new(DjangoLexer::new()),
            ),
        }
    }
}

impl Lexer for CssDjangoLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
