// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: CssGenshiLexer
// Root: CssLexer, Language: GenshiTextLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::css::CssLexer;
use crate::lexer::genshitext::GenshiTextLexer;

/// Auto-generated CssGenshiLexer lexer (DelegatingLexer).
pub struct CssGenshiLexer {
    inner: DelegatingLexer,
}

impl CssGenshiLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "CSS+Genshi Text",
                Box::new(CssLexer::new()),
                Box::new(GenshiTextLexer::new()),
            ),
        }
    }
}

impl Lexer for CssGenshiLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
