// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: DevicetreeLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated DevicetreeLexer lexer.
pub struct DevicetreeLexer {
    inner: RegexLexer,
}

impl DevicetreeLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Devicetree");
        inner.aliases = vec![
            "devicetree",
            "dts",
        ];
        inner.filenames = vec![
            "*.dts",
            "*.dtsi",
        ];
        inner.mimetypes = vec![
            "text/x-c",
        ];

        // State: macro
        inner.states.insert("macro".to_string(), vec![
        ]);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\\n", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"//(\n|[\w\W]*?[^\\]\n)", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*][\w\W]*?[*](\\\n)?/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*][\w\W]*", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // State: statements
        inner.states.insert("statements".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"(\#(?:(?:address|size)\-cells)|compatible|d(?:evice_type|ma\-ranges)|model|name|phandle|r(?:anges|eg)|status|virtual\-reg)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"([~!%^&*+=|?:<>/#-])", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"[(){},.\]]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("bytestring".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_][\w-]*(?=(?:\s*,\s*(?:/[*][^*/]*?[*]/\s*)*[a-zA-Z_][\w-]*)*\s*(?:/[*][^*/]*?[*]/\s*)*[=;])", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();


        inner.states.insert("root".to_string(), root_rules);

        // State: statement
        inner.states.insert("statement".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: node
        inner.states.insert("node".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\};", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"\\([\\abfnrtv"\']|x[a-fA-F0-9]{2,4}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|[0-7]{1,3})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\"\n]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\\\n", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\\", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: bytestring
        inner.states.insert("bytestring".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[0-9a-fA-F]{2}", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
        ]);

        DevicetreeLexer { inner }
    }
}

impl Lexer for DevicetreeLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
