// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: DnsZoneLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated DnsZoneLexer lexer.
pub struct DnsZoneLexer {
    inner: RegexLexer,
}

impl DnsZoneLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Zone");
        inner.aliases = vec![
            "zone",
        ];
        inner.filenames = vec![
            "*.zone",
        ];
        inner.mimetypes = vec![
            "text/dns",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^\$ORIGIN\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("values".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^\$TTL\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("values".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^\$INCLUDE\b", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("include".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^\$[A-Z]+\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("values".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        // State: values
        inner.states.insert("values".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("nested".to_string()) },
        ]);

        // State: nested
        inner.states.insert("nested".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: simple-value
        inner.states.insert("simple-value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"@\b", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[0-9]+[smhdw]?$", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"\S+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
        ]);

        // State: multiple-simple-values
        inner.states.insert("multiple-simple-values".to_string(), vec![
        ]);

        // State: include
        inner.states.insert("include".to_string(), vec![
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"\\""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"[^"]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        DnsZoneLexer { inner }
    }
}

impl Lexer for DnsZoneLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
