// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: EzhilLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated EzhilLexer lexer.
pub struct EzhilLexer {
    inner: RegexLexer,
}

impl EzhilLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Ezhil");
        inner.aliases = vec![
            "ezhil",
        ];
        inner.filenames = vec![
            "*.n",
        ];
        inner.mimetypes = vec![
            "text/x-ezhil",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#.*$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[@+/*,^\-%]|[!<>=]=?|&&?|\|\|?", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"இல்", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(assert|cos|ex(?:it|p)|hypot|log(?:(?:10)?)|m(?:ax|in)|p(?:i|ow)|s(?:in|qrt)|tan|எடு|கோப்பை_(?:எழுது|திற|மூடு)|சரம்_(?:இடமாற்று|கண்டுபிடி)|தலைகீழ்|ந(?:ீ(?:ட்டிக்க|ளம்)|ுழைக்க)|ப(?:ட்டியல்|ின்இணை)|வ(?:ரிசைப்படுத்து|ை))\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(True|False)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[(){}\[\]:;.]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        // State: keywords
        inner.states.insert("keywords".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"பதிப்பி|தேர்ந்தெடு|தேர்வு|ஏதேனில்|ஆனால்|இல்லைஆனால்|இல்லை|ஆக|ஒவ்வொன்றாக|இல்|வரை|செய்|முடியேனில்|பின்கொடு|முடி|நிரல்பாகம்|தொடர்|நிறுத்து|நிரல்பாகம்", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
        ]);

        // State: identifier
        inner.states.insert("identifier".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?:[a-zA-Z_]|[஀-௿])(?:[0-9]|[a-zA-Z_]|[஀-௿])*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        // State: literal
        inner.states.insert("literal".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"".*?""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\d+((\.\d*)?[eE][+-]?\d+|\.\d*)", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
        ]);

        EzhilLexer { inner }
    }
}

impl Lexer for EzhilLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
