// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: FelixLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated FelixLexer lexer.
pub struct FelixLexer {
    inner: RegexLexer,
}

impl FelixLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Felix");
        inner.aliases = vec![
            "felix",
            "flx",
        ];
        inner.filenames = vec![
            "*.flx",
            "*.flxh",
        ];
        inner.mimetypes = vec![
            "text/x-felix",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(axiom|ctor|fun|gen|proc|reduce|union)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("funcname".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(c(?:class|lass|struct)|obj|struct)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("classname".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(instance|module|typeclass)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("modulename".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(_(?:(?:deref)?)|a(?:ll|s(?:(?:sert)?)|ttempt)|c(?:a(?:ll(?:(?:back)?)|se(?:(?:no)?))|class|o(?:de|mpound)|types)|do(?:(?:ne|wnto)?)|e(?:l(?:if|se)|n(?:d(?:attempt|case|if|match)|um)|x(?:cept(?:(?:ions)?)|pect))|f(?:inally|or(?:(?:all|get|k)?)|unctor)|goto|i(?:dent|f|n(?:complete|herit|(?:stan|terfa)ce))|jump|l(?:ambda|oop)|m(?:atch|odule)|n(?:amespace|ew|o(?:expand|nterm))|o(?:bj|f|pen)|parse|r(?:aise|e(?:g(?:exp|lex|match)|name|turn))|t(?:he(?:(?:n)?)|o|ype(?:(?:case|def|match|of)?))|upto|w(?:h(?:en|ilst)|ith)|yield)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(_gc_(?:pointer|type)|body|co(?:(?:mmen|ns)t)|export|header|inline|lval|macro|no(?:inline|return)|p(?:ackage|od|r(?:ivate|operty)|ubli(?:c|sh))|requires|todo|use|virtual)\b", Token::NAME_DECORATOR).unwrap(), action: LexerAction::token(Token::NAME_DECORATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(def|let|ref|va(?:[lr]))\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(a(?:ddress|(?:n|rra)y)|b(?:ool|yte)|c(?:address|har(?:(?:(?:(?:c)?)p)?)|o(?:mplex|nt)|vaddress)|d(?:complex|imaginary|ouble)|float|i(?:maginary|nt(?:(?:16|32|64|8)?))|l(?:complex|double|i(?:maginary|st)|ong|value)|o(?:(?:ffse|p)t)|s(?:hort|lice|tring)|tiny|u(?:char(?:(?:(?:(?:c)?)p)?)|int(?:(?:16|32|64|8)?)|long|nit|s(?:hort|tring)|tiny|vlong)|v(?:a(?:ddress|rray)|long|oid|short)|w(?:char|string))\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"((?:fals|tru)e)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[xX]([0-9a-fA-F_]*\.[0-9a-fA-F_]+|[0-9a-fA-F_]+)[pP][+\-]?[0-9_]+[lLfFdD]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9_]+(\.[0-9_]+[eE][+\-]?[0-9_]+|\.[0-9_]*|[eE][+\-]?[0-9_]+)[lLfFdD]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.(0|[1-9][0-9_]*)([eE][+\-]?[0-9_]+)?[lLfFdD]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[Bb][01_]+([tTsSiIlLvV]|ll|LL|([iIuU])(8|16|32|64))?", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[0-7_]+([tTsSiIlLvV]|ll|LL|([iIuU])(8|16|32|64))?", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[xX][0-9a-fA-F_]+([tTsSiIlLvV]|ll|LL|([iIuU])(8|16|32|64))?", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(0|[1-9][0-9_]*)([tTsSiIlLvV]|ll|LL|([iIuU])(8|16|32|64))?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"([rR][cC]?|[cC][rR])""""##, Token::STRING).unwrap(), action: LexerAction::Push("tdqs".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"([rR][cC]?|[cC][rR])'''", Token::STRING).unwrap(), action: LexerAction::Push("tsqs".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"([rR][cC]?|[cC][rR])""##, Token::STRING).unwrap(), action: LexerAction::Push("dqs".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"([rR][cC]?|[cC][rR])'", Token::STRING).unwrap(), action: LexerAction::Push("sqs".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"[cCfFqQwWuU]?""""##, Token::STRING).unwrap(), action: LexerAction::Push("stringescape".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[cCfFqQwWuU]?'''", Token::STRING).unwrap(), action: LexerAction::Push("stringescape".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"[cCfFqQwWuU]?""##, Token::STRING).unwrap(), action: LexerAction::Push("stringescape".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[cCfFqQwWuU]?'", Token::STRING).unwrap(), action: LexerAction::Push("stringescape".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\[\]{}:(),;?]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*:>", Token::NAME_LABEL).unwrap(), action: LexerAction::token(Token::NAME_LABEL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(_svc|while)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(root|self|this)\b", Token::NAME_BUILTIN_PSEUDO).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });

        inner.states.insert("root".to_string(), root_rules);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("macro".to_string()) },
        ]);

        // State: operators
        inner.states.insert("operators".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(and|not|in|is|isin|or|xor)\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) },
            LexerRule { pattern: TokenPattern::new(r"!=|==|<<|>>|\|\||&&|[-~+/*%=<>&^|.$]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
        ]);

        // State: comment
        inner.states.insert("comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"//(.*?)$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"/[*]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("comment2".to_string()) },
        ]);

        // State: comment2
        inner.states.insert("comment2".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^/*]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/[*]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[/*]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // State: if0
        inner.states.insert("if0".to_string(), vec![
        ]);

        // State: macro
        inner.states.insert("macro".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^/\n]+", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"/", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\\)\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
        ]);

        // State: funcname
        inner.states.insert("funcname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_FUNCTION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?=\()", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: classname
        inner.states.insert("classname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?=\{)", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: modulename
        inner.states.insert("modulename".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("modulename2".to_string()) },
        ]);

        // State: modulename2
        inner.states.insert("modulename2".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([a-zA-Z_]\w*)", Token::NAME_NAMESPACE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: tvarlist
        inner.states.insert("tvarlist".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"(with|where)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        // State: stringescape
        inner.states.insert("stringescape".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"\\([\\abfnrtv"\']|\n|N\{.*?\}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|x[a-fA-F0-9]{2}|[0-7]{1,3})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: strings
        inner.states.insert("strings".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"%(\([a-zA-Z0-9]+\))?[-#0 +]*([0-9]+|[*])?(\.([0-9]+|[*]))?[hlL]?[E-GXc-giorsux%]", Token::STRING_INTERPOL).unwrap(), action: LexerAction::token(Token::STRING_INTERPOL) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\\'"%\n]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r#"[\'"\\]"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"%", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: nl
        inner.states.insert("nl".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\n", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: dqs
        inner.states.insert("dqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"\\\\|\\"|\\\n"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: sqs
        inner.states.insert("sqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\\\\|\\'|\\\n", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: tdqs
        inner.states.insert("tdqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: tsqs
        inner.states.insert("tsqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'''", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
        ]);

        FelixLexer { inner }
    }
}

impl Lexer for FelixLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
