// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: FishShellLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated FishShellLexer lexer.
pub struct FishShellLexer {
    inner: RegexLexer,
}

impl FishShellLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Fish");
        inner.aliases = vec![
            "fish",
            "fishshell",
        ];
        inner.filenames = vec![
            "*.fish",
            "*.load",
        ];
        inner.mimetypes = vec![
            "application/x-fish",
        ];

        // State: interp
        inner.states.insert("interp".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\$\(\(", Token::KEYWORD).unwrap(), action: LexerAction::Push("math".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::KEYWORD).unwrap(), action: LexerAction::Push("paren".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\$#?(\w+|.)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
        ]);

        // State: basic
        inner.states.insert("basic".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b(alias|bg|bind|breakpoint|builtin|command|commandline|complete|contains|dirh|dirs|emit|eval|exec|fg|fish|fish_config|fish_indent|fish_pager|fish_prompt|fish_right_prompt|fish_update_completions|fishd|funced|funcsave|functions|help|history|isatty|jobs|math|mimedb|nextd|open|popd|prevd|psub|pushd|random|read|set_color|source|status|trap|type|ulimit|umask|vared|fc|getopts|hash|kill|printf|time|wait)\s*\b(?!\.)", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"#.*\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
            LexerRule { pattern: TokenPattern::new(r"\\[\w\W]", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r"[\[\]()=]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"<<-?\s*(\'?)\\?(\w+)[\w\W]+?\2", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: data
        inner.states.insert("data".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"\$?"(\\\\|\\[0-7]+|\\.|[^"\\$])*""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\$'(\\\\|\\[0-7]+|\\.|[^'\\])*'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"'.*?'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"&|\||\^|<|>", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"\d+(?= |\Z)", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r#"[^=\s\[\]{}()$"\'`\\<&|;]+"#, Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"(\\\\|\\[0-7]+|\\.|[^"\\$])+"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
        ]);

        // State: paren
        inner.states.insert("paren".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: math
        inner.states.insert("math".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)\)", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[-+*/%^|&]|\*\*|\|\|", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"\d+#\d+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r"\d+#(?! )", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
        ]);

        FishShellLexer { inner }
    }
}

impl Lexer for FishShellLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
