// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: FlatlineLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated FlatlineLexer lexer.
pub struct FlatlineLexer {
    inner: RegexLexer,
}

impl FlatlineLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Flatline");
        inner.aliases = vec![
            "flatline",
        ];
        inner.mimetypes = vec![
            "text/x-flatline",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[,]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?\d+\.\d+", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0x-?[a-f\d]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\\(.|[a-z]+)", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"_", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(let) ", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(!=|<=|>=|a(?:bs|cos|ll(?:(?:\-(?:but|with\-(?:defaults|numeric\-default)))?)|nd|sin|tan|vg(?:(?:\-window)?))|bin\-c(?:enter|ount)|c(?:a(?:ll|tegory\-count)|eil|o(?:n(?:d\-window|[ds])|s(?:(?:h)?)|unt))|di(?:ff\-window|v)|e(?:nsure\-(?:(?:(?:weighted\-)?)value)|poch(?:(?:\-(?:day|fields|hour|m(?:i(?:llisecond|nute)|onth)|second|weekday|year))?)|xp)|f(?:i(?:eld(?:(?:\-prop|s)?)|lter|rst)|loor)|head|i(?:nteger|[fn])|l(?:anguage|e(?:ngth|venshtein)|i(?:near\-regression|st)|n|og(?:(?:10)?))|m(?:a(?:tches(?:(?:\?)?)|ximum|[px])|d5|e(?:(?:(?:di)?)an)|i(?:n(?:(?:imum)?)|ssing(?:(?:\-count|\?|_count)?))|od(?:(?:e)?))|n(?:o(?:rmalize|t)|th)|o(?:ccurrences|r)|p(?:ercentile(?:(?:\-label)?)|o(?:pulation(?:(?:\-fraction)?)|w)|referred(?:(?:\?)?))|quantile\-label|r(?:and(?:(?:\-int|om\-value)?)|e(?:\-quote|al|place(?:(?:\-first)?)|st)|o(?:und|w\-number))|s(?:egment\-label|ha(?:1|256)|in(?:(?:h)?)|q(?:rt|uare)|t(?:andard(?:(?:[\-_])deviation)|r)|u(?:bs|m(?:(?:\-(?:squares|window)|_squares|mary(?:(?:\-(?:no|str))?))?)))|t(?:a(?:il|n(?:(?:h)?))|o\-(?:(?:degree|radian)s))|v(?:(?:arianc|ectoriz)e)|w(?:eighted\-random\-value|i(?:n(?:(?:[dn])ow)|thin\-percentiles\?))|z\-score|[*+\-<=>f]) ", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<=\()(?!#)[\w!$%*+<=>?/.#-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?!#)[\w!$%*+<=>?/.#-]+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(\(|\))", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        FlatlineLexer { inner }
    }
}

impl Lexer for FlatlineLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
