// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: FloScriptLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated FloScriptLexer lexer.
pub struct FloScriptLexer {
    inner: RegexLexer,
}

impl FloScriptLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("FloScript");
        inner.aliases = vec![
            "floscript",
            "flo",
        ];
        inner.filenames = vec![
            "*.flo",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[]{}:(),;[]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\\", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(to|by|with|from|per|for|cum|qua|via|as|at|in|of|on|re|is|if|be|into|and|not)\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"!=|==|<<|>>|[-~+/*%=<>&^|.]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(load|init|server|logger|log|loggee|first|over|under|next|done|timeout|repeat|native|benter|enter|recur|exit|precur|renter|rexit|print|put|inc|copy|set|aux|rear|raze|go|let|do|bid|ready|start|stop|run|abort|use|flo|give|take)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(frame|framer|house)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::Push("string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#.+$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });

        inner.states.insert("root".to_string(), root_rules);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"[^"]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: numbers
        inner.states.insert("numbers".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(\d+\.\d*|\d*\.\d+)([eE][+-]?[0-9]+)?j?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"\d+[eE][+-]?[0-9]+j?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"0[0-7]+j?", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"0[bB][01]+", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) },
            LexerRule { pattern: TokenPattern::new(r"0[xX][a-fA-F0-9]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"\d+L", Token::NUMBER_INTEGER_LONG).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER_LONG) },
            LexerRule { pattern: TokenPattern::new(r"\d+j?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
        ]);

        // State: name
        inner.states.insert("name".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"@[\w.]+", Token::NAME_DECORATOR).unwrap(), action: LexerAction::token(Token::NAME_DECORATOR) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        FloScriptLexer { inner }
    }
}

impl Lexer for FloScriptLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
