// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: GasLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated GasLexer lexer.
pub struct GasLexer {
    inner: RegexLexer,
}

impl GasLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("GAS");
        inner.aliases = vec![
            "gas",
            "asm",
        ];
        inner.filenames = vec![
            "*.s",
            "*.S",
        ];
        inner.mimetypes = vec![
            "text/x-gas",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+):", Token::NAME_LABEL).unwrap(), action: LexerAction::token(Token::NAME_LABEL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+)", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::Push("directive-args".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"lock|rep(n?z)?|data\d+", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+)", Token::NAME_FUNCTION).unwrap(), action: LexerAction::Push("instruction-args".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\r\n]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: directive-args
        inner.states.insert("directive-args".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+)", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r##""(\\"|[^"])*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"@(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+)", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) },
            LexerRule { pattern: TokenPattern::new(r"(?:0[xX][a-fA-F0-9]+|#?-?\d+)", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"%(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+)\b", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"([;#]|//).*?\n", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"/[*].*?[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/[*].*?\n[\w\W]*?[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: instruction-args
        inner.states.insert("instruction-args".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+)", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r"(?:0[xX][a-fA-F0-9]+|#?-?\d+)", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"%(?:[a-zA-Z$_][\w$.@-]*|\.[\w$.@-]+)\b", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"$(?:0[xX][a-fA-F0-9]+|#?-?\d+)", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"$'(.|\\')'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) },
            LexerRule { pattern: TokenPattern::new(r"([;#]|//).*?\n", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"/[*].*?[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/[*].*?\n[\w\W]*?[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([;#]|//).*?\n", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"/[*][\w\W]*?[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // State: punctuation
        inner.states.insert("punctuation".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[-*,.()\[\]!:{}]+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        GasLexer { inner }
    }
}

impl Lexer for GasLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
