// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: GraphQLLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated GraphQLLexer lexer.
pub struct GraphQLLexer {
    inner: RegexLexer,
}

impl GraphQLLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("GraphQL");
        inner.aliases = vec![
            "graphql",
        ];
        inner.filenames = vec![
            "*.graphql",
        ];

        // State: ignored_tokens
        inner.states.insert("ignored_tokens".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#.*$", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: value
        inner.states.insert("value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"-?\d+(?![.eE])", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"-?\d+(\.\d+)?([eE][+-]?\d+)?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(false|null|true)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\$[a-zA-Z_]\w*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_CONSTANT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: list_value
        inner.states.insert("list_value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: object_value
        inner.states.insert("object_value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
            LexerRule { pattern: TokenPattern::new(r":", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("value".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"\\(["\\/bfnrt]|u[a-fA-F0-9]{4})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\"\n]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(mutation|query|subscription)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("operation".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(ARGUMENT_DEFINITION|ENUM(?:(?:_VALUE)?)|F(?:IELD(?:(?:_DEFINITION)?)|RAGMENT_(?:DEFINITION|SPREAD))|IN(?:LINE_FRAGMENT|PUT_(?:FIELD_DEFINITION|OBJECT)|TERFACE)|MUTATION|OBJECT|QUERY|S(?:C(?:ALAR|HEMA)|UBSCRIPTION)|UNION|directive|e(?:num|xtend)|i(?:mplements|n(?:put|terface))|sc(?:alar|hema)|type|union)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("selection_set".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"fragment\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("fragment_definition".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        // State: operation
        inner.states.insert("operation".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("variable_definition".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: variable_definition
        inner.states.insert("variable_definition".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\$[a-zA-Z_]\w*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"[\]!]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r":", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("type".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"=", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("value".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: type
        inner.states.insert("type".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"(Boolean|Float|I(?:D|nt)|String)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: selection_set
        inner.states.insert("selection_set".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
            LexerRule { pattern: TokenPattern::new(r"\.\.\.", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("fragment_spread".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("arguments".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"@[a-zA-Z_]\w*", Token::NAME_DECORATOR).unwrap(), action: LexerAction::Push("directive".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("selection_set".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: directive
        inner.states.insert("directive".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: arguments
        inner.states.insert("arguments".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
            LexerRule { pattern: TokenPattern::new(r":", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("value".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: fragment_definition
        inner.states.insert("fragment_definition".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[\]!]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"on\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("type".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"@[a-zA-Z_]\w*", Token::NAME_DECORATOR).unwrap(), action: LexerAction::Push("directive".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: fragment_spread
        inner.states.insert("fragment_spread".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"@[a-zA-Z_]\w*", Token::NAME_DECORATOR).unwrap(), action: LexerAction::Push("directive".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: inline_fragment
        inner.states.insert("inline_fragment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
            LexerRule { pattern: TokenPattern::new(r"@[a-zA-Z_]\w*", Token::NAME_DECORATOR).unwrap(), action: LexerAction::Push("directive".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        GraphQLLexer { inner }
    }
}

impl Lexer for GraphQLLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
