// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: GraphvizLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated GraphvizLexer lexer.
pub struct GraphvizLexer {
    inner: RegexLexer,
}

impl GraphvizLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Graphviz");
        inner.aliases = vec![
            "graphviz",
            "dot",
        ];
        inner.filenames = vec![
            "*.gv",
            "*.dot",
        ];
        inner.mimetypes = vec![
            "text/x-graphviz",
            "text/vnd.graphviz",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(#|//).*?$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*](.|\n)*?[*](\\\n)?/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(node|edge|graph|digraph|subgraph|strict)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"--|->", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[{}[\]:;,]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(n|ne|e|se|s|sw|w|nw|c|_)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b\D\w*", Token::NAME_TAG).unwrap(), action: LexerAction::token(Token::NAME_TAG) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[-]?((\.[0-9]+)|([0-9]+(\.[0-9]*)?))", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(\\"|[^"])*?""##, Token::NAME_TAG).unwrap(), action: LexerAction::token(Token::NAME_TAG) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"<", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("xml".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        // State: attr_id
        inner.states.insert("attr_id".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b\D\w*", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[-]?((\.[0-9]+)|([0-9]+(\.[0-9]*)?))", Token::NUMBER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r##""(\\"|[^"])*?""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"<", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: xml
        inner.states.insert("xml".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"<", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r">", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^<>\s]", Token::NAME_TAG).unwrap(), action: LexerAction::token(Token::NAME_TAG) },
        ]);

        GraphvizLexer { inner }
    }
}

impl Lexer for GraphvizLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
