// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: HandlebarsLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated HandlebarsLexer lexer.
pub struct HandlebarsLexer {
    inner: RegexLexer,
}

impl HandlebarsLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Handlebars");
        inner.aliases = vec![
            "handlebars",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[^{]+", Token::OTHER).unwrap(), action: LexerAction::token(Token::OTHER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{\{!.*\}\}", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: tag
        inner.states.insert("tag".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"\}\}\}", Token::COMMENT_SPECIAL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: dynamic-partial
        inner.states.insert("dynamic-partial".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[\w-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
        ]);

        // State: variable
        inner.states.insert("variable".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[()/@a-zA-Z][\w-]*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\.[\w-]+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"(this\/|\.\/|(\.\.\/)+)[\w-]+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
        ]);

        // State: generic
        inner.states.insert("generic".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##":?"(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r":?'(\\\\|\\[^\\]|[^'\\])*'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"[0-9](\.[0-9]*)?(eE[+-][0-9])?[flFLdD]?|0[xX][0-9a-fA-F]+[Ll]?", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
        ]);

        HandlebarsLexer { inner }
    }
}

impl Lexer for HandlebarsLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
