// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: IniLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated IniLexer lexer.
pub struct IniLexer {
    inner: RegexLexer,
}

impl IniLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("INI");
        inner.aliases = vec![
            "ini",
            "cfg",
            "dosini",
        ];
        inner.filenames = vec![
            "*.ini",
            "*.cfg",
            "*.inf",
            ".editorconfig",
        ];
        inner.mimetypes = vec![
            "text/x-ini",
            "text/inf",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[;#].*", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(.+?)$", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) });

        inner.states.insert("root".to_string(), root_rules);

        // State: quoted_value
        inner.states.insert("quoted_value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[;#].*", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"$", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: value
        inner.states.insert("value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r".*$", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
        ]);

        IniLexer { inner }
    }
}

impl Lexer for IniLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
