// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: IoLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated IoLexer lexer.
pub struct IoLexer {
    inner: RegexLexer,
}

impl IoLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Io");
        inner.aliases = vec![
            "io",
        ];
        inner.filenames = vec![
            "*.io",
        ];
        inner.mimetypes = vec![
            "text/x-iosrc",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"//(.*?)$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#(.*?)$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*](.|\n)*?[*](\\\n)?/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\+", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("nestedcomment".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"::=|:=|=|\(|\)|;|,|\*|-|\+|>|<|@|!|/|\||\^|\.|%|&|\[|\]|\{|\}", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(clone|do|doFile|doString|method|for|if|else|elseif|then)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(nil|false|true)\b", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(Object|list|List|Map|args|Sequence|Coroutine|File)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(\d+\.?\d*|\d*\.\d+)([eE][+-]?[0-9]+)?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });

        inner.states.insert("root".to_string(), root_rules);

        // State: nestedcomment
        inner.states.insert("nestedcomment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^+/]+", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/\+", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\+/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[+/]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        IoLexer { inner }
    }
}

impl Lexer for IoLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
