// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: KalLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated KalLexer lexer.
pub struct KalLexer {
    inner: RegexLexer,
}

impl KalLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Kal");
        inner.aliases = vec![
            "kal",
        ];
        inner.filenames = vec![
            "*.kal",
        ];
        inner.mimetypes = vec![
            "text/kal",
            "application/kal",
        ];

        // State: commentsandwhitespace
        inner.states.insert("commentsandwhitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"###[^#].*?###", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // State: functiondef
        inner.states.insert("functiondef".to_string(), vec![
        ]);

        // State: classdef
        inner.states.insert("classdef".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([$a-zA-Z_][\w$]*)(?=\s*\n)", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[$a-zA-Z_][\w$]*\b", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
        ]);

        // State: listcomprehension
        inner.states.insert("listcomprehension".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\b(property|value)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
        ]);

        // State: waitfor
        inner.states.insert("waitfor".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\bfrom\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/(?! )(\\.|[^[/\\\n]|\[(\\.|[^\]\\\n])*])+/([gimuysd]+\b|\B)", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\?|:|_(?=\n)|==?|!=|-(?!>)|[<>+*/-]=?", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(and|or|isnt|is|not|but|bitwise|mod|\^|xor|exists|doesnt\s+exist)\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[{(]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("listcomprehension".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[})\].,]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(function|method|task)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::Push("functiondef".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\bclass\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::Push("classdef".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(me|this)(\.[$a-zA-Z_][\w.$]*)?\b", Token::NAME_VARIABLE_INSTANCE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_INSTANCE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<![.$])(break|c(?:atch|ontinue)|delete|else|finally|i(?:nstanceof|[fn])|new|o(?:f|therwise)|r(?:aise|eturn)|super|t(?:hrow|ry|ypeof)|un(?:less|til)|wh(?:en|ile))\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<![.$])(Infinity|NaN|false|n(?:o(?:(?:ne|thing)?)|ull)|o(?:ff|n)|true|undefined|yes)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(Array|Boolean|Date|Error|Function|Math|Number|Object|RegExp|S(?:tring|ymbol)|d(?:ecodeURI(?:(?:Component)?)|ocument)|e(?:ncodeURI(?:(?:Component)?)|val)|globalThis|is(?:Finite|NaN|SafeInteger)|p(?:(?:arse(?:Floa|In)|rin)t)|window)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9][0-9]*\.[0-9]+([eE][0-9]+)?[fd]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"""""##, Token::STRING).unwrap(), action: LexerAction::Push("tdqs".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'''", Token::STRING).unwrap(), action: LexerAction::Push("tsqs".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::Push("dqs".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'", Token::STRING).unwrap(), action: LexerAction::Push("sqs".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        // State: strings
        inner.states.insert("strings".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"[^#\\\'"]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: interpoling_string
        inner.states.insert("interpoling_string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: dqs
        inner.states.insert("dqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\\.|\'", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"#\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("interpoling_string".to_string()) },
        ]);

        // State: sqs
        inner.states.insert("sqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r##"#|\\.|""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: tdqs
        inner.states.insert("tdqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r##"\\.|\'|""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"#\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("interpoling_string".to_string()) },
        ]);

        // State: tsqs
        inner.states.insert("tsqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'''", Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r##"#|\\.|\'|""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        KalLexer { inner }
    }
}

impl Lexer for KalLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
