// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: LassoJavascriptLexer
// Root: JavascriptLexer, Language: LassoLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::javascript::JavaScriptLexer;
use crate::lexer::lasso::LassoLexer;

/// Auto-generated LassoJavascriptLexer lexer (DelegatingLexer).
pub struct LassoJavascriptLexer {
    inner: DelegatingLexer,
}

impl LassoJavascriptLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "JavaScript+Lasso",
                Box::new(JavaScriptLexer::new()),
                Box::new(LassoLexer::new()),
            ),
        }
    }
}

impl Lexer for LassoJavascriptLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
