// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: MozPreprocHashLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated MozPreprocHashLexer lexer.
pub struct MozPreprocHashLexer {
    inner: RegexLexer,
}

impl MozPreprocHashLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("mozhashpreproc");
        inner.aliases = vec![
            "mozhashpreproc",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^#", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("expr".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r".+", Token::OTHER).unwrap(), action: LexerAction::token(Token::OTHER) });

        inner.states.insert("root".to_string(), root_rules);

        // State: exprstart
        inner.states.insert("exprstart".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(define|e(?:l(?:if(?:(?:(?:(?:n)?)def)?)|se)|ndif|rror|xpand)|filter|i(?:f(?:(?:(?:(?:n)?)def)?)|nclude(?:(?:subst)?))|un(?:def|filter))", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: expr
        inner.states.insert("expr".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(!(?:(?:=)?)|\&\&|==|\|\|)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"__\w+?__", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"@\w+?@", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
            LexerRule { pattern: TokenPattern::new(r"\w+", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"\S", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        MozPreprocHashLexer { inner }
    }
}

impl Lexer for MozPreprocHashLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
