// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: MozPreprocJavascriptLexer
// Root: JavascriptLexer, Language: MozPreprocHashLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::javascript::JavaScriptLexer;
use crate::lexer::mozpreprochash::MozPreprocHashLexer;

/// Auto-generated MozPreprocJavascriptLexer lexer (DelegatingLexer).
pub struct MozPreprocJavascriptLexer {
    inner: DelegatingLexer,
}

impl MozPreprocJavascriptLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "Javascript+mozpreproc",
                Box::new(JavaScriptLexer::new()),
                Box::new(MozPreprocHashLexer::new()),
            ),
        }
    }
}

impl Lexer for MozPreprocJavascriptLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
