// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: MozPreprocCssLexer
// Root: CssLexer, Language: MozPreprocPercentLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::css::CssLexer;
use crate::lexer::mozpreprocpercent::MozPreprocPercentLexer;

/// Auto-generated MozPreprocCssLexer lexer (DelegatingLexer).
pub struct MozPreprocCssLexer {
    inner: DelegatingLexer,
}

impl MozPreprocCssLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "CSS+mozpreproc",
                Box::new(CssLexer::new()),
                Box::new(MozPreprocPercentLexer::new()),
            ),
        }
    }
}

impl Lexer for MozPreprocCssLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
