// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: NasmObjdumpLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated NasmObjdumpLexer lexer.
pub struct NasmObjdumpLexer {
    inner: RegexLexer,
}

impl NasmObjdumpLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("objdump-nasm");
        inner.aliases = vec![
            "objdump-nasm",
        ];
        inner.filenames = vec![
            "*.objdump-intel",
        ];
        inner.mimetypes = vec![
            "text/x-nasm-objdump",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\t\.\.\.$", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[^\n]+\n", Token::OTHER).unwrap(), action: LexerAction::token(Token::OTHER) });

        inner.states.insert("root".to_string(), root_rules);

        NasmObjdumpLexer { inner }
    }
}

impl Lexer for NasmObjdumpLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
