// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: NewspeakLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated NewspeakLexer lexer.
pub struct NewspeakLexer {
    inner: RegexLexer,
}

impl NewspeakLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Newspeak");
        inner.aliases = vec![
            "newspeak",
        ];
        inner.filenames = vec![
            "*.ns2",
        ];
        inner.mimetypes = vec![
            "text/x-newspeak",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(Newsqueak2)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'[^']*'", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(mixin|self|super|private|public|protected|nil|true|false)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"<\w+>", Token::COMMENT_SPECIAL).unwrap(), action: LexerAction::token(Token::COMMENT_SPECIAL) });

        inner.states.insert("root".to_string(), root_rules);

        // State: expressionstat
        inner.states.insert("expressionstat".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(\d+\.\d*|\.\d+|\d+[fF])[fF]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r":\w+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\w+:", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"\w+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\(|\)", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\[|\]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\{|\}", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"(\^|\+|\/|~|\*|<|>|=|@|%|\||&|\?|!|,|-|:)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"\.|;", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: literals
        inner.states.insert("literals".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\$.", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"'[^']*'", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"#'[^']*'", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r"#\w+:?", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r"#(\+|\/|~|\*|<|>|=|@|%|\||&|\?|!|,|-)+", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
        ]);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r##""[^"]*""##, Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        NewspeakLexer { inner }
    }
}

impl Lexer for NewspeakLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
