// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: ObjectiveJLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated ObjectiveJLexer lexer.
pub struct ObjectiveJLexer {
    inner: RegexLexer,
}

impl ObjectiveJLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Objective-J");
        inner.aliases = vec![
            "objective-j",
            "objectivej",
            "obj-j",
            "objj",
        ];
        inner.filenames = vec![
            "*.j",
        ];
        inner.mimetypes = vec![
            "text/x-objective-j",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[{()}]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#if\s+0", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("if0".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("macro".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"//(\n|(.|\n)*?[^\\]\n)", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*](.|\n)*?[*](\\\n)?/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"<!--", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        // State: slashstartsregex
        inner.states.insert("slashstartsregex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"/(\\.|[^[/\\\n]|\[(\\.|[^\]\\\n])*])+/([gim]+\b|\B)", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?=/)", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: badregex
        inner.states.insert("badregex".to_string(), vec![
        ]);

        // State: statements
        inner.states.insert("statements".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"(L|@)?""##, Token::STRING).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(L|@)?'(\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) },
            LexerRule { pattern: TokenPattern::new(r##""(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r"'(\\\\|\\[^\\]|[^'\\])*'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"(\d+\.\d*|\.\d+|\d+)[eE][+-]?\d+[lL]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"(\d+\.\d*|\.\d+|\d+[fF])[fF]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+[Ll]?", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"0[0-7]+[Ll]?", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"\d+[Ll]?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"^(?=\s|/|<!--)", Token::TEXT).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\+\+|--|~|&&|\?|:|\|\||\\(?=\n)|(<<|>>>?|==?|!=?|[-<>+*%&|^/])=?", Token::OPERATOR).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[{(\[;,]", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[})\].]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"(for|in|while|do|break|return|continue|switch|case|default|if|else|throw|try|catch|finally|new|delete|typeof|instanceof|void|prototype|__proto__)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(var|with|function)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(@selector|@private|@protected|@public|@encode|@synchronized|@try|@throw|@catch|@finally|@end|@property|@synthesize|@dynamic|@for|@accessors|new)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(int|long|float|short|double|char|unsigned|signed|void|id|BOOL|bool|boolean|IBOutlet|IBAction|SEL|@outlet|@action)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"(self|super)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"(TRUE|YES|FALSE|NO|Nil|nil|NULL)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r"(true|false|null|NaN|Infinity|undefined)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r"(ABS|ASIN|ACOS|ATAN|ATAN2|SIN|COS|TAN|EXP|POW|CEIL|FLOOR|ROUND|MIN|MAX|RAND|SQRT|E|LN2|LN10|LOG2E|LOG10E|PI|PI2|PI_2|SQRT1_2|SQRT2)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r"(Array|Boolean|Date|Error|Function|Math|Number|Object|RegExp|String|decodeURI|decodeURIComponent|encodeURI|encodeURIComponent|Error|eval|isFinite|isNaN|parseFloat|parseInt|document|this|window|globalThis|Symbol)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"[$a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        // State: classname
        inner.states.insert("classname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([a-zA-Z_]\w*)", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: forward_classname
        inner.states.insert("forward_classname".to_string(), vec![
        ]);

        // State: function_signature
        inner.states.insert("function_signature".to_string(), vec![
        ]);

        // State: function_parameters
        inner.states.insert("function_parameters".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([$a-zA-Z_]\w+(?:\s|//[^\n]*\n|/[*](?:[^*]|[*][^/])*[*]/)*:)", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(:)", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"([$a-zA-Z_]\w+)", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        // State: expression
        inner.states.insert("expression".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(\))", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"\\([\\abfnrtv"\']|x[a-fA-F0-9]{2,4}|[0-7]{1,3})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\"\n]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\\", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: macro
        inner.states.insert("macro".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^/\n]+", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"/[*](.|\n)*?[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
        ]);

        // State: if0
        inner.states.insert("if0".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"^\s*#if.*?(?<!\\)\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"^\s*#endif.*?(?<!\\)\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::PopN(1) },
        ]);

        ObjectiveJLexer { inner }
    }
}

impl Lexer for ObjectiveJLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
