// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: ObjectiveCppLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated ObjectiveCppLexer lexer.
pub struct ObjectiveCppLexer {
    inner: RegexLexer,
}

impl ObjectiveCppLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Objective-C++");
        inner.aliases = vec![
            "objective-c++",
            "objectivec++",
            "obj-c++",
            "objc++",
        ];
        inner.filenames = vec![
            "*.mm",
            "*.hh",
        ];
        inner.mimetypes = vec![
            "text/x-objective-c++",
        ];

        // State: statements
        inner.states.insert("statements".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"@""##, Token::STRING).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"@(YES|NO)", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r"@'(\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) },
            LexerRule { pattern: TokenPattern::new(r"@(\d+\.\d*|\.\d+|\d+)[eE][+-]?\d+[lL]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"@(\d+\.\d*|\.\d+|\d+[fF])[fF]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"@0x[0-9a-fA-F]+[Ll]?", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"@0[0-7]+[Ll]?", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"@\d+[Ll]?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"@\(", Token::LITERAL).unwrap(), action: LexerAction::Push("literal_number".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"@\[", Token::LITERAL).unwrap(), action: LexerAction::Push("literal_array".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"@\{", Token::LITERAL).unwrap(), action: LexerAction::Push("literal_dictionary".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(@(?:autoreleasepool|catch|dynamic|en(?:code|d)|finally|import|optional|p(?:r(?:ivate|o(?:perty|tected))|ublic)|required|s(?:elector|yn(?:chronized|thesize))|t(?:hrow|ry))|__(?:autoreleasing|b(?:lock|ridge(?:(?:_transfer)?))|strong|weak)|a(?:ssign|tomic)|c(?:lass|opy)|getter|in(?:(?:out)?)|nonatomic|out|re(?:ad(?:only|write)|lease|tain)|s(?:etter|trong)|typeof|unsafe_unretained|weak)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(BOOL|Class|I(?:B(?:Action|Outlet)|MP)|SEL|i(?:d|nstancetype)|unichar)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"@(true|false|YES|NO)\n", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"(YES|NO|nil|self|super)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"(Boolean|UInt8|SInt8|UInt16|SInt16|UInt32|SInt32)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"(TRUE|FALSE)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"@", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"0[xX]([0-9a-fA-F](\'?[0-9a-fA-F])*\.[0-9a-fA-F](\'?[0-9a-fA-F])*|\.[0-9a-fA-F](\'?[0-9a-fA-F])*|[0-9a-fA-F](\'?[0-9a-fA-F])*)[pP][+-]?[0-9a-fA-F](\'?[0-9a-fA-F])*[lL]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"(-)?(\d(\'?\d)*\.\d(\'?\d)*|\.\d(\'?\d)*|\d(\'?\d)*)[eE][+-]?\d(\'?\d)*[fFlL]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"(-)?((\d(\'?\d)*\.(\d(\'?\d)*)?|\.\d(\'?\d)*)[fFlL]?)|(\d(\'?\d)*[fFlL])", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"(-)?0[xX][0-9a-fA-F](\'?[0-9a-fA-F])*(([uU]?[zZ])|([zZ][uU])|([uU][lL]{0,2})|([lL]{1,2}[uU]?))?", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"(-)?0[bB][01](\'?[01])*(([uU]?[zZ])|([zZ][uU])|([uU][lL]{0,2})|([lL]{1,2}[uU]?))?", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) },
            LexerRule { pattern: TokenPattern::new(r"(-)?0(\'?[0-7])+(([uU]?[zZ])|([zZ][uU])|([uU][lL]{0,2})|([lL]{1,2}[uU]?))?", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"(-)?\d(\'?\d)*(([uU]?[zZ])|([zZ][uU])|([uU][lL]{0,2})|([lL]{1,2}[uU]?))?", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"[~!%^&*+=|?:<>/-]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"[()\[\],.]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"(true|false|NULL|nullptr)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        // State: oc_classname
        inner.states.insert("oc_classname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"([a-zA-Z$_][\w$]*)", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: oc_forward_classname
        inner.states.insert("oc_forward_classname".to_string(), vec![
        ]);

        // State: oc_ivars
        inner.states.insert("oc_ivars".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"__(e(?:vent|xtends)|finally|i(?:mplements|nterface)|multiple_inheritance|null|s(?:ingle_inheritance|uper)|uuidof|virtual_inheritance)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"__(offload|blockingoffload|outer)\b", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) });

        inner.states.insert("root".to_string(), root_rules);

        // State: method
        inner.states.insert("method".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\.\.\.", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z$_][\w$]*:", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("function".to_string()) },
        ]);

        // State: literal_number
        inner.states.insert("literal_number".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("literal_number_inner".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::LITERAL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: literal_number_inner
        inner.states.insert("literal_number_inner".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: literal_array
        inner.states.insert("literal_array".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("literal_array_inner".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::LITERAL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: literal_array_inner
        inner.states.insert("literal_array_inner".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: literal_dictionary
        inner.states.insert("literal_dictionary".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::LITERAL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: enumname
        inner.states.insert("enumname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(class|struct)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\s*(?=>)", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: keywords
        inner.states.insert("keywords".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(__restrict|and(?:(?:_eq)?)|bit(?:and|or)|c(?:atch|lass|o(?:_(?:await|return|yield)|mpl|n(?:cept|st(?:_cast|eval|init)|tract_assert)))|d(?:e(?:(?:cltyp|let)e)|ynamic_cast)|exp(?:(?:lici|or)t)|f(?:inal|riend)|import|m(?:(?:odu|utab)le)|n(?:ew|o(?:except|t(?:(?:_eq)?)))|o(?:perator|r(?:(?:_eq)?)|verride)|p(?:ost|r(?:e|ivate|otected)|ublic)|re(?:interpret_cast|quires)|static_cast|t(?:emplate|h(?:is|row(?:(?:s)?))|ry|ype(?:id|name))|using|virtual|xor(?:(?:_eq)?))\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"namespace\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("namespace".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"case\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("case-value".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(_Pragma|a(?:lign(?:as|of)|sm|uto)|break|con(?:st(?:(?:expr)?)|tinue)|d(?:efault|o)|e(?:lse|num|xtern)|for(?:(?:tran)?)|goto|if|re(?:gister|stricted|turn)|s(?:izeof|t(?:atic(?:(?:_assert)?)|ruct)|witch)|t(?:hread_local|ype(?:def|of(?:(?:_unqual)?)))|union|(?:volat|wh)ile)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(_(?:(?:(?:_)?)inline)|inline|naked|restrict|thread)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"(__m(128i|128d|128|64))\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"__(as(?:m|sume)|based|cdecl|declspec|except|f(?:astcall|inally|orceinline)|identifier|leave|n(?:oop|ull)|raise|stdcall|try|unaligned|w64)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
        ]);

        // State: types
        inner.states.insert("types".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"char(16_t|32_t|8_t)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"__(int(?:16|32|64|8)|wchar_t)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"(_(?:BitInt|_int128)|bool|char|double|float|int|long|s(?:hort|igned)|(?:unsigne|voi)d)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
        ]);

        // State: namespace
        inner.states.insert("namespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[;{]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"inline\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+", Token::NAME_NAMESPACE).unwrap(), action: LexerAction::token(Token::NAME_NAMESPACE) },
        ]);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"^#if\s+0", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("if0".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"^#", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("macro".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\\\n", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"//(?:.|(?<=\\)\n)*\n", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*][\w\W]*", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // State: statement
        inner.states.insert("statement".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[{;]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: function
        inner.states.insert("function".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"\\([\\abfnrtv"\']|x[a-fA-F0-9]{2,4}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|[0-7]{1,3})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\"\n]+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\\\n", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\\", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: macro
        inner.states.insert("macro".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^/\n]+", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"/[*](.|\n)*?[*]/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"//.*?\n", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"/", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\\)\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: if0
        inner.states.insert("if0".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"^\s*#if.*?(?<!\\)\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"^\s*#el(?:se|if).*\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"^\s*#endif.*?(?<!\\)\n", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r".*?\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        // State: classname
        inner.states.insert("classname".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\s*(?=>)", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: case-value
        inner.states.insert("case-value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?<!:)(:)(?!:)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) },
        ]);

        ObjectiveCppLexer { inner }
    }
}

impl Lexer for ObjectiveCppLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
