// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: OocLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated OocLexer lexer.
pub struct OocLexer {
    inner: RegexLexer,
}

impl OocLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Ooc");
        inner.aliases = vec![
            "ooc",
        ];
        inner.filenames = vec![
            "*.ooc",
        ];
        inner.mimetypes = vec![
            "text/x-ooc",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(a(?:bstract|s)|break|c(?:ase|lass|on(?:st|tinue))|do|e(?:lse|xte(?:nds|rn))|f(?:al(?:lthrough|se)|inal|or|rom)|i(?:mp(?:(?:lemen|or)t)|n(?:(?:lin|terfac)e)|[fn])|n(?:ew|ull)|operator|proto|return|s(?:tatic|uper|witch)|t(?:his|rue)|use|version|while)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"include\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("include".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\bfunc\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"//.*", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\*.*?\*/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(==?|\+=?|-[=>]?|\*=?|/=?|:=|!=?|%=?|\?|>{1,3}=?|<{1,3}=?|\.\.|&&?|\|\|?|\^=?)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[A-Z][A-Z0-9_]+", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[A-Z]\w*([@*]|\[[ \t]*\])?", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-z]\w*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[:(){}\[\];,]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0c[0-9]+", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0b[01]+", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9_]\.[0-9_]*(?!\.)", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(?:\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\"])*""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'(?:\\.|\\[0-9]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\\[ \t\n]", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[ \t]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: include
        inner.states.insert("include".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[\w/]+", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[ \t]", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"[;\n]", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        OocLexer { inner }
    }
}

impl Lexer for OocLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
