// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: OpaLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated OpaLexer lexer.
pub struct OpaLexer {
    inner: RegexLexer,
}

impl OpaLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Opa");
        inner.aliases = vec![
            "opa",
        ];
        inner.filenames = vec![
            "*.opa",
        ];
        inner.mimetypes = vec![
            "text/x-opa",
        ];

        // State: escape-sequence
        inner.states.insert("escape-sequence".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"\\[\\"\'ntr}]"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r"\\[0-9]{3}", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r"\\x[0-9a-fA-F]{2}", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: comments
        inner.states.insert("comments".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"/\*", Token::COMMENT).unwrap(), action: LexerAction::Push("nested-comment".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"//.*?$", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        // State: comments-and-spaces
        inner.states.insert("comments-and-spaces".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(a(?:nd|s)|begin|c(?:ase|lient|ss)|d(?:atabase|[bo])|e(?:lse|nd|xternal)|f(?:orall|unction)|i(?:f|mport)|m(?:atch|odule)|or|pa(?:ckage|rser)|rec|server|t(?:hen|ype)|val|with|xml_parser)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@(([a-zA-Z_]\w*)|(`[^`]*`))\b", Token::NAME_BUILTIN_PSEUDO).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?.[\d]+([eE][+\-]?\d+)", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?\d+.\d*([eE][+\-]?\d+)", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?\d+[eE][+\-]?\d+", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[xX][\da-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[oO][0-7]+", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[bB][01]+", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#[\da-fA-F]{3,6}", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r#"'(?:(\\[\\\"'ntbr ])|(\\[0-9]{3})|(\\x[0-9a-fA-F]{2})|.)'"#, Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{", Token::OPERATOR).unwrap(), action: LexerAction::Push("root".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\}", Token::OPERATOR).unwrap(), action: LexerAction::PopN(1) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"<(?=[a-zA-Z>])", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("html-open-tag".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[@?!]?(/\w+)+(\[_\])?", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"<-(?![.=\-<>,@~%/+?*&^!])", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b([A-Z]\w*)(?=\.)", Token::NAME_NAMESPACE).unwrap(), action: LexerAction::token(Token::NAME_NAMESPACE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"=(?![.=\-<>,@~%/+?*&^!])", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"([.=\-<>,@~%/+?*&^!])+", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"([()\[\],;|])+", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r":", Token::OPERATOR).unwrap(), action: LexerAction::Push("type".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'(([a-zA-Z_]\w*)|(`[^`]*`))", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#(([a-zA-Z_]\w*)|(`[^`]*`))", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#(?=\{)", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(([a-zA-Z_]\w*)|(`[^`]*`))", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: type
        inner.states.insert("type".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"->", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
        ]);

        // State: type-1
        inner.states.insert("type-1".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"~?\{", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(([a-zA-Z_]\w*)|(`[^`]*`))\(", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(([a-zA-Z_]\w*)|(`[^`]*`))", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"'(([a-zA-Z_]\w*)|(`[^`]*`))", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
        ]);

        // State: slash-type-1
        inner.states.insert("slash-type-1".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"/", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: type-lhs-1
        inner.states.insert("type-lhs-1".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"->", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?=,)", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: type-arrow
        inner.states.insert("type-arrow".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r",(?=[^:]*?->)", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::Push("type-with-slash".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"->", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: type-tuple
        inner.states.insert("type-tuple".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^()/*]+", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"[/*]", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"\(", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: type-record
        inner.states.insert("type-record".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^{}/*]+", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"[/*]", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: nested-comment
        inner.states.insert("nested-comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^/*]+", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
            LexerRule { pattern: TokenPattern::new(r"/\*", Token::COMMENT).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\*/", Token::COMMENT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[/*]", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"[^\\"{]+"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::OPERATOR).unwrap(), action: LexerAction::Push("root".to_string()) },
        ]);

        // State: single-string
        inner.states.insert("single-string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^\\\'{]+", Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r"\'", Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::OPERATOR).unwrap(), action: LexerAction::Push("root".to_string()) },
        ]);

        // State: html-open-tag
        inner.states.insert("html-open-tag".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[\w\-:]+", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r">", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: html-end-tag
        inner.states.insert("html-end-tag".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[\w\-:]*>", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: html-attr
        inner.states.insert("html-attr".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"[\w\-:]+=", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("html-attr-value".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"/>", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r">", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: html-attr-value
        inner.states.insert("html-attr-value".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"#(([a-zA-Z_]\w*)|(`[^`]*`))", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"#(?=\{)", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"[^"\'{`=<>]+"#, Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::OPERATOR).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: html-content
        inner.states.insert("html-content".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"<!--", Token::COMMENT).unwrap(), action: LexerAction::Push("html-comment".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"</", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"<", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("html-open-tag".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::OPERATOR).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[^<{]+", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
        ]);

        // State: html-comment
        inner.states.insert("html-comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"-->", Token::COMMENT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^\-]+|-", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        OpaLexer { inner }
    }
}

impl Lexer for OpaLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
