// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: PrqlLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated PrqlLexer lexer.
pub struct PrqlLexer {
    inner: RegexLexer,
}

impl PrqlLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("PRQL");
        inner.aliases = vec![
            "prql",
        ];
        inner.filenames = vec![
            "*.prql",
        ];
        inner.mimetypes = vec![
            "application/prql",
            "application/x-prql",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#!.*", Token::STRING_DOC).unwrap(), action: LexerAction::token(Token::STRING_DOC) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#.*", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(bool|float|int(?:(?:1(?:28|6)|32|64|8)?)|(?:se|tex)t)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^prql ", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"let", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^[A-Za-z_][a-zA-Z0-9_]*", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });

        inner.states.insert("root".to_string(), root_rules);

        // State: expr
        inner.states.insert("expr".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("stringescape".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"'''", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("stringescape".to_string()) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("stringescape".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("stringescape".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"@\d{4}-\d{2}-\d{2}T\d{2}(:\d{2})?(:\d{2})?(\.\d{1,6})?(Z|[+-]\d{1,2}(:\d{1,2})?)?", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
            LexerRule { pattern: TokenPattern::new(r"@\d{4}-\d{2}-\d{2}", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
            LexerRule { pattern: TokenPattern::new(r"@\d{2}(:\d{2})?(:\d{2})?(\.\d{1,6})?(Z|[+-]\d{1,2}(:\d{1,2})?)?", Token::LITERAL_DATE).unwrap(), action: LexerAction::token(Token::LITERAL_DATE) },
            LexerRule { pattern: TokenPattern::new(r"[^\S\n]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"->|=>|==|!=|>=|<=|~=|&&|\|\||\?\?|\/\/", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"[-~+/*%=<>&^|.@]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"[]{}:(),;[]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[A-Za-z_][a-zA-Z0-9_]*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
        ]);

        // State: numbers
        inner.states.insert("numbers".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(\d(?:_?\d)*\.(?:\d(?:_?\d)*)?|(?:\d(?:_?\d)*)?\.\d(?:_?\d)*)([eE][+-]?\d(?:_?\d)*)?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"\d(?:_?\d)*[eE][+-]?\d(?:_?\d)*j?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"0[oO](?:_?[0-7])+", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"0[bB](?:_?[01])+", Token::NUMBER_BIN).unwrap(), action: LexerAction::token(Token::NUMBER_BIN) },
            LexerRule { pattern: TokenPattern::new(r"0[xX](?:_?[a-fA-F0-9])+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"\d(?:_?\d)*", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
        ]);

        // State: bytesescape
        inner.states.insert("bytesescape".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r#"\\([\\bfnrt"\']|\n|x[a-fA-F0-9]{2}|[0-7]{1,3})"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: stringescape
        inner.states.insert("stringescape".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\(N\{.*?\}|u\{[a-fA-F0-9]{1,6}\})", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: fstrings-single
        inner.states.insert("fstrings-single".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::token(Token::STRING_INTERPOL) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("expr-inside-fstring".to_string()) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\\'"{}\n]+"#, Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r#"[\'"\\]"#, Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
        ]);

        // State: fstrings-double
        inner.states.insert("fstrings-double".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::token(Token::STRING_INTERPOL) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::STRING_INTERPOL).unwrap(), action: LexerAction::Push("expr-inside-fstring".to_string()) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\\'"{}\n]+"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r#"[\'"\\]"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
        ]);

        // State: strings-single
        inner.states.insert("strings-single".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\{((\w+)((\.\w+)|(\[[^\]]+\]))*)?(\:(.?[<>=\^])?[-+ ]?#?0?(\d+)?,?(\.\d+)?[E-GXb-gnosx%]?)?\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::token(Token::STRING_INTERPOL) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\\'"%{\n]+"#, Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r#"[\'"\\]"#, Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"%|(\{{1,2})", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
        ]);

        // State: strings-double
        inner.states.insert("strings-double".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\{((\w+)((\.\w+)|(\[[^\]]+\]))*)?(\:(.?[<>=\^])?[-+ ]?#?0?(\d+)?,?(\.\d+)?[E-GXb-gnosx%]?)?\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::token(Token::STRING_INTERPOL) },
            LexerRule { pattern: TokenPattern::new(r#"[^\\\'"%{\n]+"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r#"[\'"\\]"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r"%|(\{{1,2})", Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
        ]);

        // State: dqf
        inner.states.insert("dqf".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"\\\\|\\"|\\\n"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: sqf
        inner.states.insert("sqf".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\\\\|\\'|\\\n", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: dqs
        inner.states.insert("dqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r#"\\\\|\\"|\\\n"#, Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: sqs
        inner.states.insert("sqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\\\\|\\'|\\\n", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
        ]);

        // State: tdqf
        inner.states.insert("tdqf".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
        ]);

        // State: tsqf
        inner.states.insert("tsqf".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'''", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
        ]);

        // State: tdqs
        inner.states.insert("tdqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
        ]);

        // State: tsqs
        inner.states.insert("tsqs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'''", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
        ]);

        // State: expr-inside-fstring
        inner.states.insert("expr-inside-fstring".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[{([]", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("expr-inside-fstring-inner".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(=\s*)?\}", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(=\s*)?:", Token::STRING_INTERPOL).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: expr-inside-fstring-inner
        inner.states.insert("expr-inside-fstring-inner".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[{([]", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("expr-inside-fstring-inner".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[])}]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: keywords
        inner.states.insert("keywords".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(case|int(?:ernal|o)|(?:modul|typ)e)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(false|null|true)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) },
        ]);

        // State: functions
        inner.states.insert("functions".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(_(?:eq|is_null)|a(?:ny|s|verage)|co(?:ncat_array|unt)|every|f(?:(?:irs|rom_tex)t)|in|l(?:a(?:g|st)|ead|ower)|m(?:ax|in)|r(?:ank(?:(?:_dense)?)|ead_(?:csv|parquet)|o(?:und|w_number))|s(?:tddev|um)|tuple_(?:every|(?:ma|zi)p)|upper)\b", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
        ]);

        // State: comment
        inner.states.insert("comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"-(?!\})", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"\{-", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("comment".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[^-}]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"-\}", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: imports
        inner.states.insert("imports".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\w+(\.\w+)*", Token::NAME_CLASS).unwrap(), action: LexerAction::PopN(1) },
        ]);

        PrqlLexer { inner }
    }
}

impl Lexer for PrqlLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
