// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: PtxLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated PtxLexer lexer.
pub struct PtxLexer {
    inner: RegexLexer,
}

impl PtxLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("PTX");
        inner.aliases = vec![
            "ptx",
        ];
        inner.filenames = vec![
            "*.ptx",
        ];
        inner.mimetypes = vec![
            "text/x-ptx",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r#"(([-a-zA-Z$._][\w\-$.]*|"[^"]*?")|(\d+))\s*:"#, Token::NAME_LABEL).unwrap(), action: LexerAction::token(Token::NAME_LABEL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r#"%([-a-zA-Z$._][\w\-$.]*|"[^"]*?")"#, Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"c?"[^"]*?""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r#"([-a-zA-Z$._][\w\-$.]*|"[^"]*?")"#, Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r";", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[*+-/]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0[xX][a-fA-F0-9]+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-?\d+(?:[.]\d+)?(?:[eE][-+]?\d+(?:[.]\d+)?)?", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[=<>{}\[\]()*.,!]|x\b", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"//.*?\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        // State: keyword
        inner.states.insert("keyword".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(a(?:bs|ctivemask|dd(?:(?:c)?)|lloca|nd|pplypriority|tom)|b(?:ar(?:(?:rier)?)|f(?:ind|[ei])|msk|r(?:ev|kpt|[ax]))|c(?:all|lz|not|o(?:pysign|s)|p|reatepolicy|vt(?:(?:a)?))|d(?:i(?:scard|v)|p(?:(?:[24])a))|e(?:lect|x(?:2|it))|f(?:ence|ma|ns)|g(?:etctarank|riddepcontrol)|is(?:(?:spac|typ)ep)|l(?:d(?:(?:matrix|u)?)|g2|op3)|m(?:a(?:d(?:24|c)|pa|tch|[dx])|barrier|embar|in|ma|ov(?:(?:matrix)?)|ul(?:(?:24|timem)?))|n(?:anosleep|eg|ot)|or|p(?:mevent|opc|r(?:efetch(?:(?:u)?)|mt))|r(?:cp|e(?:dux|[dmt])|sqrt)|s(?:ad|e(?:lp|t(?:(?:maxnreg|p)?))|h(?:fl|[flr])|in|lct|qrt|t(?:(?:ack(?:(?:restor|sav)e)|matrix)?)|u(?:bc|ld|red|st|[bq])|zext)|t(?:anh|e(?:stp|x)|ld4|rap|xq)|v(?:a(?:bsdiff(?:(?:[24])?)|dd(?:(?:[24])?)|vrg(?:[24]))|m(?:a(?:x(?:[24])|[dx])|in(?:(?:[24])?))|ote|s(?:et(?:(?:[24])?)|h(?:[lr])|ub(?:(?:[24])?)))|w(?:(?:(?:g)?)mma)|xor)", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(\.(?:const|global|loc(?:(?:al)?)|param|s(?:hared|reg)|tex|wide)|reg)", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) },
            LexerRule { pattern: TokenPattern::new(r"(\.(?:a(?:ddress_size|li(?:as|gn))|branchtargets|c(?:all(?:prototype|targets)|o(?:mmon|nst))|e(?:ntry|x(?:plicitcluster|tern))|f(?:ile|unc)|global|loc(?:(?:al)?)|m(?:ax(?:clusterrank|n(?:ctapersm|reg|tid))|innctapersm)|noreturn|p(?:aram|ragma)|re(?:g|qn(?:ctapercluster|tid))|s(?:ection|hared|reg)|t(?:arget|ex)|v(?:ersion|isible)|weak))", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"(\.(?:b(?:16|32|64|8)|f(?:16(?:(?:x2)?)|32|64)|pred|s(?:16|32|64|8)|u(?:16|32|64|8)))", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
        ]);

        PtxLexer { inner }
    }
}

impl Lexer for PtxLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
