// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: PythonUL4Lexer
// Root: PythonLexer, Language: UL4Lexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::python::PythonLexer;
use crate::lexer::ul4::UL4Lexer;

/// Auto-generated PythonUL4Lexer lexer (DelegatingLexer).
pub struct PythonUL4Lexer {
    inner: DelegatingLexer,
}

impl PythonUL4Lexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "Python+UL4",
                Box::new(PythonLexer::new()),
                Box::new(UL4Lexer::new()),
            ),
        }
    }
}

impl Lexer for PythonUL4Lexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
