// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: QmlLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated QmlLexer lexer.
pub struct QmlLexer {
    inner: RegexLexer,
}

impl QmlLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("QML");
        inner.aliases = vec![
            "qml",
            "qbs",
        ];
        inner.filenames = vec![
            "*.qml",
            "*.qbs",
        ];
        inner.mimetypes = vec![
            "application/x-qml",
            "application/x-qt.qbs+qml",
        ];

        // State: commentsandwhitespace
        inner.states.insert("commentsandwhitespace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"<!--", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
            LexerRule { pattern: TokenPattern::new(r"//.*?\n", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"/\*.*?\*/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // State: slashstartsregex
        inner.states.insert("slashstartsregex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"/(\\.|[^[/\\\n]|\[(\\.|[^\]\\\n])*])+/([gim]+\b|\B)", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?=/)", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: badregex
        inner.states.insert("badregex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\n", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^(?=\s|/|<!--)", Token::TEXT).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\+\+|--|~|&&|\?|:|\|\||\\(?=\n)|(<<|>>>?|==?|!=?|[-<>+*%&|^/])=?", Token::OPERATOR).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[{(\[;,]", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[})\].]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\bid\s*:\s*[A-Za-z][\w.]*", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b[A-Za-z][\w.]*\s*:", Token::KEYWORD).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(for|in|while|do|break|return|continue|switch|case|default|if|else|throw|try|catch|finally|new|delete|typeof|instanceof|void|this)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(var|let|with|function)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::Push("slashstartsregex".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(abstract|boolean|byte|char|class|const|debugger|double|enum|export|extends|final|float|goto|implements|import|int|interface|long|native|package|private|protected|public|short|static|super|synchronized|throws|transient|volatile)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(true|false|null|NaN|Infinity|undefined)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(Array|Boolean|Date|Error|Function|Math|netscape|Number|Object|Packages|RegExp|String|sun|decodeURI|decodeURIComponent|encodeURI|encodeURIComponent|Error|eval|isFinite|isNaN|parseFloat|parseInt|document|this|window)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[$a-zA-Z_]\w*", Token::NAME_OTHER).unwrap(), action: LexerAction::token(Token::NAME_OTHER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9][0-9]*\.[0-9]+([eE][0-9]+)?[fd]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'(\\\\|\\[^\\]|[^'\\])*'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) });

        inner.states.insert("root".to_string(), root_rules);

        QmlLexer { inner }
    }
}

impl Lexer for QmlLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
