// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// DelegatingLexer: RhtmlLexer
// Root: HtmlLexer, Language: ErbLexer

use crate::lexer::{Lexer, DelegatingLexer};
use crate::lexer::htmlxml::HtmlLexer;
use crate::lexer::erb::ErbLexer;

/// Auto-generated RhtmlLexer lexer (DelegatingLexer).
pub struct RhtmlLexer {
    inner: DelegatingLexer,
}

impl RhtmlLexer {
    pub fn new() -> Self {
        Self {
            inner: DelegatingLexer::new(
                "RHTML",
                Box::new(HtmlLexer::new()),
                Box::new(ErbLexer::new()),
            ),
        }
    }
}

impl Lexer for RhtmlLexer {
    fn get_tokens(&self, code: &str) -> Vec<(crate::token::Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &[]
    }

    fn filenames(&self) -> &[&str] {
        &[]
    }

    fn mimetypes(&self) -> &[&str] {
        &[]
    }
}
