// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: RqlLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated RqlLexer lexer.
pub struct RqlLexer {
    inner: RegexLexer,
}

impl RqlLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("RQL");
        inner.aliases = vec![
            "rql",
        ];
        inner.filenames = vec![
            "*.rql",
        ];
        inner.mimetypes = vec![
            "text/x-rql",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(DELETE|SET|INSERT|UNION|DISTINCT|WITH|WHERE|BEING|OR|AND|NOT|GROUPBY|HAVING|ORDERBY|ASC|DESC|LIMIT|OFFSET|TODAY|NOW|TRUE|FALSE|NULL|EXISTS)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[+*/<>=%-]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(Any|is|instance_of|CWEType|CWRelation)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[A-Z_]\w*\??", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'(''|[^'])*'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""(""|[^"])*""##, Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[;:()\[\],.]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });

        inner.states.insert("root".to_string(), root_rules);

        RqlLexer { inner }
    }
}

impl Lexer for RqlLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
