// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: RslLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated RslLexer lexer.
pub struct RslLexer {
    inner: RegexLexer,
}

impl RslLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("RSL");
        inner.aliases = vec![
            "rsl",
        ];
        inner.filenames = vec![
            "*.rsl",
        ];
        inner.mimetypes = vec![
            "text/rsl",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(\-(?:(?:inf(?:lis|se)|lis|se)t)|Bool|Char|Int|Nat|Real|Text|Unit|a(?:bs|l(?:l|ways)|ny|s|xiom)|c(?:a(?:rd|se)|ha(?:nnel|os)|lass)|d(?:evt_relation|om)|e(?:l(?:ems|if|se)|nd|x(?:ists|tend))|f(?:alse|or)|h(?:d|ide)|i(?:n(?:ds|itialise|t(?:(?:er)?))|sin|[fns])|l(?:e(?:[nt])|ocal|tl_assertion)|o(?:bject|f|ut)|p(?:ost|re)|r(?:ea(?:[dl])|ng)|s(?:cheme|(?:ki|to|wa)p)|t(?:est_case|he(?:n|ory)|l|r(?:ansition_system|ue)|ype)|u(?:n(?:ion|til)|se)|va(?:(?:lu|riabl)e)|w(?:hile|ith|rite)|\~isin)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(variable|value)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"--.*?\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"<:.*?:>", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{!.*?!\}", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\*.*?\*/", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b[A-Z]\w*\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(true|false)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"".*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\'.\'", Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(><|->|-m->|/\\|<=|<<=|<\.|\|\||\|\^\||-~->|-~m->|\\/|>=|>>|\.>|\+\+|-\\|<->|=>|:-|~=|\*\*|<<|>>=|\+>|!!|\|=\||#)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+\.[0-9]+([eE][0-9]+)?[fd]?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0x[0-9a-f]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9]+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r".", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        RslLexer { inner }
    }
}

impl Lexer for RslLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
