// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: ScdocLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated ScdocLexer lexer.
pub struct ScdocLexer {
    inner: RegexLexer,
}

impl ScdocLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("scdoc");
        inner.aliases = vec![
            "scdoc",
            "scd",
        ];
        inner.filenames = vec![
            "*.scd",
            "*.scdoc",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();


        inner.states.insert("root".to_string(), root_rules);

        // State: inline
        inner.states.insert("inline".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\.", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"`[^`]+`", Token::STRING_BACKTICK).unwrap(), action: LexerAction::token(Token::STRING_BACKTICK) },
            LexerRule { pattern: TokenPattern::new(r"[^\\\s]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r".", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        ScdocLexer { inner }
    }
}

impl Lexer for ScdocLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
