// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: SnowballLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated SnowballLexer lexer.
pub struct SnowballLexer {
    inner: RegexLexer,
}

impl SnowballLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Snowball");
        inner.aliases = vec![
            "snowball",
        ];
        inner.filenames = vec![
            "*.sbl",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"len\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"lenof\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) });

        inner.states.insert("root".to_string(), root_rules);

        // State: root1
        inner.states.insert("root1".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"[()]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"/\*[\w\W]*?\*/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"//.*", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"[!*+\-/<=>]=|[-=]>|<[+-]|[$*+\-/<=>?\[\]]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"(a(?:mong|s)|backwardmode|de(?:cimal|fine)|get|hex)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) },
            LexerRule { pattern: TokenPattern::new(r"((?:boolean|external|grouping|integer|routine|string)s)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::Push("declaration".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(a(?:nd|t(?:l(?:(?:eas|imi)t)|mark|tach))|backwards|d(?:elete|o)|f(?:a(?:il|lse)|or)|go(?:past|to)|hop|insert|loop|n(?:ext|o(?:[nt]))|or|re(?:peat|verse)|s(?:et(?:(?:limit|mark)?)|izeof|ubstring)|t(?:est|o(?:limit|mark)|r(?:ue|y))|unset)\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) },
            LexerRule { pattern: TokenPattern::new(r"(cursor|limit|m(?:(?:ax|in)int)|size)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"[A-Za-z]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        // State: declaration
        inner.states.insert("declaration".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(len(?:(?:of)?))\b", Token::NAME).unwrap(), action: LexerAction::Push("root1".to_string()) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
        ]);

        // State: escape
        inner.states.insert("escape".to_string(), vec![
        ]);

        SnowballLexer { inner }
    }
}

impl Lexer for SnowballLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
