// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: SoongLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated SoongLexer lexer.
pub struct SoongLexer {
    inner: RegexLexer,
}

impl SoongLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Soong");
        inner.aliases = vec![
            "androidbp",
            "bp",
            "soong",
        ];
        inner.filenames = vec![
            "Android.bp",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();


        inner.states.insert("root".to_string(), root_rules);

        // State: assign-rhs
        inner.states.insert("assign-rhs".to_string(), vec![
        ]);

        // State: in-list
        inner.states.insert("in-list".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: in-map
        inner.states.insert("in-map".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r",", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"\}", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: comments
        inner.states.insert("comments".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"//.*", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"/(\\\n)?[*](.|\n)*?[*](\\\n)?/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // State: expr
        inner.states.insert("expr".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(true|false)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r##"".*?""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("in-map".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("in-list".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\w+", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        SoongLexer { inner }
    }
}

impl Lexer for SoongLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
