// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: SourcesListLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated SourcesListLexer lexer.
pub struct SourcesListLexer {
    inner: RegexLexer,
}

impl SourcesListLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Debian Sourcelist");
        inner.aliases = vec![
            "debsources",
            "sourceslist",
            "sources.list",
        ];
        inner.filenames = vec![
            "sources.list",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#.*?$", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: distribution
        inner.states.insert("distribution".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#.*?$", Token::COMMENT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\$\(ARCH\)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"[^\s$[]+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::STRING_OTHER).unwrap(), action: LexerAction::Push("escaped-distribution".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\$", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: escaped-distribution
        inner.states.insert("escaped-distribution".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\]", Token::STRING_OTHER).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\$\(ARCH\)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"[^\]$]+", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
            LexerRule { pattern: TokenPattern::new(r"\$", Token::STRING_OTHER).unwrap(), action: LexerAction::token(Token::STRING_OTHER) },
        ]);

        // State: components
        inner.states.insert("components".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#.*?$", Token::COMMENT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"$", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\S+", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) },
        ]);

        SourcesListLexer { inner }
    }
}

impl Lexer for SourcesListLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
