// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: TalLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated TalLexer lexer.
pub struct TalLexer {
    inner: RegexLexer,
}

impl TalLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Tal");
        inner.aliases = vec![
            "tal",
            "uxntal",
        ];
        inner.filenames = vec![
            "*.tal",
        ];
        inner.mimetypes = vec![
            "text/x-uxntal",
        ];

        // State: comment
        inner.states.insert("comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(?<!\S)\((?!\S)", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(?<!\S)\)(?!\S)", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^()]+", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"[()]+", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<!\S)\((?!\S)", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("comment".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<!\S)(A(?:(?:[DN])D)|BRK|D(?:E(?:[IO])|IV|UP)|E(?:OR|QU)|GTH|INC|J(?:CN|MP|SR)|L(?:D(?:[ARZ])|IT|TH)|MUL|N(?:EQ|IP)|O(?:RA|VR)|POP|ROT|S(?:FT|T(?:[AHRZ])|UB|WP))2?k?r?(?!\S)", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[][{}](?!\S)", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"#([0-9a-f]{2}){1,2}(?!\S)", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r#""\S+"#, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"([0-9a-f]{2}){1,2}(?!\S)", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[|$][0-9a-f]{1,4}(?!\S)", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"%\S+", Token::NAME_DECORATOR).unwrap(), action: LexerAction::token(Token::NAME_DECORATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"@\S+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"&\S+", Token::NAME_LABEL).unwrap(), action: LexerAction::token(Token::NAME_LABEL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\S+", Token::NAME_TAG).unwrap(), action: LexerAction::token(Token::NAME_TAG) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\.\S+", Token::NAME_VARIABLE_MAGIC).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_MAGIC) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r",\S+", Token::NAME_VARIABLE_INSTANCE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_INSTANCE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r";\S+", Token::NAME_VARIABLE_GLOBAL).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE_GLOBAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"-\S+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"_\S+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"=\S+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"!\S+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\?\S+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"~\S+", Token::KEYWORD_NAMESPACE).unwrap(), action: LexerAction::token(Token::KEYWORD_NAMESPACE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\S+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) });

        inner.states.insert("root".to_string(), root_rules);

        TalLexer { inner }
    }
}

impl Lexer for TalLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
