// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: TAPLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated TAPLexer lexer.
pub struct TAPLexer {
    inner: RegexLexer,
}

impl TAPLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("TAP");
        inner.aliases = vec![
            "tap",
        ];
        inner.filenames = vec![
            "*.tap",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^TAP version \d+\n", Token::NAME_NAMESPACE).unwrap(), action: LexerAction::token(Token::NAME_NAMESPACE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^1\.\.\d+", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::Push("plan".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^#.*\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^Bail out!.*\n", Token::GENERIC_ERROR).unwrap(), action: LexerAction::token(Token::GENERIC_ERROR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^.*\n", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        // State: plan
        inner.states.insert("plan".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^\S\n]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT).unwrap(), action: LexerAction::Push("directive".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::COMMENT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r".*\n", Token::GENERIC_ERROR).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: test
        inner.states.insert("test".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^\S\n]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT).unwrap(), action: LexerAction::Push("directive".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\S+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: directive
        inner.states.insert("directive".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^\S\n]+", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
            LexerRule { pattern: TokenPattern::new(r"\bTODO\b", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"\bSKIP\S*", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"\S+", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::COMMENT).unwrap(), action: LexerAction::PopN(1) },
        ]);

        TAPLexer { inner }
    }
}

impl Lexer for TAPLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
