// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: TclLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated TclLexer lexer.
pub struct TclLexer {
    inner: RegexLexer,
}

impl TclLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Tcl");
        inner.aliases = vec![
            "tcl",
        ];
        inner.filenames = vec![
            "*.tcl",
            "*.rvt",
        ];
        inner.mimetypes = vec![
            "text/x-tcl",
            "text/x-script.tcl",
            "application/x-tcl",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\}", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });

        inner.states.insert("root".to_string(), root_rules);

        // State: command
        inner.states.insert("command".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b(a(?:fter|(?:ppl|rra)y)|break|c(?:atch|ontinue)|e(?:lse(?:(?:if)?)|rror|val|xpr)|for(?:(?:each)?)|global|if|namespace|proc|re(?:name|turn)|s(?:et|witch)|t(?:hen|race)|u(?:nset|p(?:date|level|var))|v(?:ariable|wait)|while)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("params".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\b(append|b(?:gerror|inary)|c(?:d|han|lo(?:ck|se)|oncat)|d(?:de|ict)|e(?:ncoding|of|x(?:ec|it))|f(?:blocked|co(?:nfigure|py)|ile(?:(?:event)?)|lush|ormat)|g(?:ets|lob)|h(?:istory|ttp)|in(?:cr|fo|terp)|join|l(?:a(?:ppend|ssign)|i(?:n(?:dex|sert)|st)|length|oad(?:(?:Tk)?)|r(?:ange|e(?:p(?:eat|lace)|verse))|s(?:e(?:arch|t)|ort))|m(?:ath(?:func|op)|emory|sgcat)|open|p(?:ackage|id|kg(?:::create|_mkIndex)|latform(?:(?:::shell)?)|uts|wd)|re(?:_syntax|ad|fchan|g(?:exp|istry|sub))|s(?:can|eek|o(?:cket|urce)|plit|tring|ubst)|t(?:ell|ime|m)|un(?:known|load))\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::Push("params".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"([\w.-]+)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::Push("params".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT).unwrap(), action: LexerAction::Push("comment".to_string()) },
        ]);

        // State: command-in-brace
        inner.states.insert("command-in-brace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b(a(?:fter|(?:ppl|rra)y)|break|c(?:atch|ontinue)|e(?:lse(?:(?:if)?)|rror|val|xpr)|for(?:(?:each)?)|global|if|namespace|proc|re(?:name|turn)|s(?:et|witch)|t(?:hen|race)|u(?:nset|p(?:date|level|var))|v(?:ariable|wait)|while)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("params-in-brace".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\b(append|b(?:gerror|inary)|c(?:d|han|lo(?:ck|se)|oncat)|d(?:de|ict)|e(?:ncoding|of|x(?:ec|it))|f(?:blocked|co(?:nfigure|py)|ile(?:(?:event)?)|lush|ormat)|g(?:ets|lob)|h(?:istory|ttp)|in(?:cr|fo|terp)|join|l(?:a(?:ppend|ssign)|i(?:n(?:dex|sert)|st)|length|oad(?:(?:Tk)?)|r(?:ange|e(?:p(?:eat|lace)|verse))|s(?:e(?:arch|t)|ort))|m(?:ath(?:func|op)|emory|sgcat)|open|p(?:ackage|id|kg(?:::create|_mkIndex)|latform(?:(?:::shell)?)|uts|wd)|re(?:_syntax|ad|fchan|g(?:exp|istry|sub))|s(?:can|eek|o(?:cket|urce)|plit|tring|ubst)|t(?:ell|ime|m)|un(?:known|load))\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::Push("params-in-brace".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"([\w.-]+)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::Push("params-in-brace".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT).unwrap(), action: LexerAction::Push("comment".to_string()) },
        ]);

        // State: command-in-bracket
        inner.states.insert("command-in-bracket".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b(a(?:fter|(?:ppl|rra)y)|break|c(?:atch|ontinue)|e(?:lse(?:(?:if)?)|rror|val|xpr)|for(?:(?:each)?)|global|if|namespace|proc|re(?:name|turn)|s(?:et|witch)|t(?:hen|race)|u(?:nset|p(?:date|level|var))|v(?:ariable|wait)|while)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("params-in-bracket".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\b(append|b(?:gerror|inary)|c(?:d|han|lo(?:ck|se)|oncat)|d(?:de|ict)|e(?:ncoding|of|x(?:ec|it))|f(?:blocked|co(?:nfigure|py)|ile(?:(?:event)?)|lush|ormat)|g(?:ets|lob)|h(?:istory|ttp)|in(?:cr|fo|terp)|join|l(?:a(?:ppend|ssign)|i(?:n(?:dex|sert)|st)|length|oad(?:(?:Tk)?)|r(?:ange|e(?:p(?:eat|lace)|verse))|s(?:e(?:arch|t)|ort))|m(?:ath(?:func|op)|emory|sgcat)|open|p(?:ackage|id|kg(?:::create|_mkIndex)|latform(?:(?:::shell)?)|uts|wd)|re(?:_syntax|ad|fchan|g(?:exp|istry|sub))|s(?:can|eek|o(?:cket|urce)|plit|tring|ubst)|t(?:ell|ime|m)|un(?:known|load))\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::Push("params-in-bracket".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"([\w.-]+)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::Push("params-in-bracket".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT).unwrap(), action: LexerAction::Push("comment".to_string()) },
        ]);

        // State: command-in-paren
        inner.states.insert("command-in-paren".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\b(a(?:fter|(?:ppl|rra)y)|break|c(?:atch|ontinue)|e(?:lse(?:(?:if)?)|rror|val|xpr)|for(?:(?:each)?)|global|if|namespace|proc|re(?:name|turn)|s(?:et|witch)|t(?:hen|race)|u(?:nset|p(?:date|level|var))|v(?:ariable|wait)|while)\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("params-in-paren".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\b(append|b(?:gerror|inary)|c(?:d|han|lo(?:ck|se)|oncat)|d(?:de|ict)|e(?:ncoding|of|x(?:ec|it))|f(?:blocked|co(?:nfigure|py)|ile(?:(?:event)?)|lush|ormat)|g(?:ets|lob)|h(?:istory|ttp)|in(?:cr|fo|terp)|join|l(?:a(?:ppend|ssign)|i(?:n(?:dex|sert)|st)|length|oad(?:(?:Tk)?)|r(?:ange|e(?:p(?:eat|lace)|verse))|s(?:e(?:arch|t)|ort))|m(?:ath(?:func|op)|emory|sgcat)|open|p(?:ackage|id|kg(?:::create|_mkIndex)|latform(?:(?:::shell)?)|uts|wd)|re(?:_syntax|ad|fchan|g(?:exp|istry|sub))|s(?:can|eek|o(?:cket|urce)|plit|tring|ubst)|t(?:ell|ime|m)|un(?:known|load))\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::Push("params-in-paren".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"([\w.-]+)", Token::NAME_VARIABLE).unwrap(), action: LexerAction::Push("params-in-paren".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"#", Token::COMMENT).unwrap(), action: LexerAction::Push("comment".to_string()) },
        ]);

        // State: basic
        inner.states.insert("basic".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::KEYWORD).unwrap(), action: LexerAction::Push("paren".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\[", Token::KEYWORD).unwrap(), action: LexerAction::Push("bracket".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\{", Token::KEYWORD).unwrap(), action: LexerAction::Push("brace".to_string()) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(eq|ne|in|ni)\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) },
            LexerRule { pattern: TokenPattern::new(r"!=|==|<<|>>|<=|>=|&&|\|\||\*\*|[-+~!*/%<>&^|?:]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
        ]);

        // State: data
        inner.states.insert("data".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"0x[a-fA-F0-9]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"0[0-7]+", Token::NUMBER_OCT).unwrap(), action: LexerAction::token(Token::NUMBER_OCT) },
            LexerRule { pattern: TokenPattern::new(r"\d+\.\d+", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"\$[\w.:-]+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\$\{[\w.:-]+\}", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"[\w.,@:-]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        // State: params
        inner.states.insert("params".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r";", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"\n", Token::TEXT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(else|elseif|then)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
        ]);

        // State: params-in-brace
        inner.states.insert("params-in-brace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: params-in-paren
        inner.states.insert("params-in-paren".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: params-in-bracket
        inner.states.insert("params-in-bracket".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\]", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string-square".to_string()) },
            LexerRule { pattern: TokenPattern::new(r#"(\\\\|\\[0-7]+|\\.|[^"\\])"#, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string-square
        inner.states.insert("string-square".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\[", Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string-square".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(\\\\|\\[0-7]+|\\.|\\\n|[^\]\\])", Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r"\]", Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: brace
        inner.states.insert("brace".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\}", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: paren
        inner.states.insert("paren".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\)", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: bracket
        inner.states.insert("bracket".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\]", Token::KEYWORD).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: comment
        inner.states.insert("comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r".*[^\\]\n", Token::COMMENT).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r".*\\\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        TclLexer { inner }
    }
}

impl Lexer for TclLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
