// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: TermcapLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated TermcapLexer lexer.
pub struct TermcapLexer {
    inner: RegexLexer,
}

impl TermcapLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Termcap");
        inner.aliases = vec![
            "termcap",
        ];
        inner.filenames = vec![
            "termcap",
            "termcap.src",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^#.*", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"^[^\s#:|]+", Token::NAME_TAG).unwrap(), action: LexerAction::Push("names".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        // State: names
        inner.states.insert("names".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r":", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("defs".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\|", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[^:|]+", Token::NAME_ATTRIBUTE).unwrap(), action: LexerAction::token(Token::NAME_ATTRIBUTE) },
        ]);

        // State: defs
        inner.states.insert("defs".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"=", Token::OPERATOR).unwrap(), action: LexerAction::Push("data".to_string()) },
            LexerRule { pattern: TokenPattern::new(r":", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[^\s:=#]+", Token::NAME_CLASS).unwrap(), action: LexerAction::token(Token::NAME_CLASS) },
        ]);

        // State: data
        inner.states.insert("data".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\072", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
            LexerRule { pattern: TokenPattern::new(r":", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[^:\\]+", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
            LexerRule { pattern: TokenPattern::new(r".", Token::LITERAL).unwrap(), action: LexerAction::token(Token::LITERAL) },
        ]);

        TermcapLexer { inner }
    }
}

impl Lexer for TermcapLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
