// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: TwigLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated TwigLexer lexer.
pub struct TwigLexer {
    inner: RegexLexer,
}

impl TwigLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Twig");
        inner.aliases = vec![
            "twig",
        ];
        inner.mimetypes = vec![
            "application/x-twig",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[^{]+", Token::OTHER).unwrap(), action: LexerAction::token(Token::OTHER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{\{", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::Push("var".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{\#.*?\#\}", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{", Token::OTHER).unwrap(), action: LexerAction::token(Token::OTHER) });

        inner.states.insert("root".to_string(), root_rules);

        // State: varnames
        inner.states.insert("varnames".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(true|false|none|null)\b", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) },
            LexerRule { pattern: TokenPattern::new(r"(in|not|and|b-and|or|b-or|b-xor|isif|elseif|else|importconstant|defined|divisibleby|empty|even|iterable|odd|sameasmatches|starts\s+with|ends\s+with)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(loop|block|parent)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) },
            LexerRule { pattern: TokenPattern::new(r"(?:[\\_a-z]|[^\x00-\x7f])(?:[\\\w-]|[^\x00-\x7f])*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\.(?:[\\_a-z]|[^\x00-\x7f])(?:[\\\w-]|[^\x00-\x7f])*", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
            LexerRule { pattern: TokenPattern::new(r"\.[0-9]+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r##":?"(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::token(Token::STRING_DOUBLE) },
            LexerRule { pattern: TokenPattern::new(r":?'(\\\\|\\[^\\]|[^'\\])*'", Token::STRING_SINGLE).unwrap(), action: LexerAction::token(Token::STRING_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"([{}()\[\]+\-*/,:~%]|\.\.|\?|:|\*\*|\/\/|!=|[><=]=?)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"[0-9](\.[0-9]*)?(eE[+-][0-9])?[flFLdD]?|0[xX][0-9a-fA-F]+[Ll]?", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
        ]);

        // State: var
        inner.states.insert("var".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
        ]);

        // State: tag
        inner.states.insert("tag".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) },
            LexerRule { pattern: TokenPattern::new(r".", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        TwigLexer { inner }
    }
}

impl Lexer for TwigLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
