// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: UcodeLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated UcodeLexer lexer.
pub struct UcodeLexer {
    inner: RegexLexer,
}

impl UcodeLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("ucode");
        inner.aliases = vec![
            "ucode",
        ];
        inner.filenames = vec![
            "*.u",
            "*.u1",
            "*.u2",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(#.*\n)", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(con|declend|end|global|i(?:mpl|nvocable)|l(?:ab|ink|ocal)|record|u(?:id|nions)|version)\b", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(colm|filen|line|synt)\b", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(asgn|b(?:ang|scan)|c(?:at|case|hfail|o(?:act|fail|mpl|ret)|reate|set)|d(?:i(?:ff|v)|up)|e(?:fail|init|nd|qv|r(?:et|ror)|s(?:can|usp))|field|goto|in(?:it|t(?:(?:er)?)|voke)|keywd|l(?:concat|ex(?:eq|g(?:[et])|l(?:[et])|ne)|imit|list|susp)|m(?:ark(?:(?:0)?)|inus|od|ult)|n(?:e(?:g|qv)|o(?:nnull|op)|u(?:ll|m(?:ber|eq|g(?:[et])|l(?:[et])|ne)))|p(?:fail|lus|null|o(?:p|wer)|r(?:et|oc)|susp|ush(?:(?:(?:n)?)1))|r(?:a(?:ndom|sgn)|cv(?:(?:bk)?)|e(?:al|fresh)|swap)|s(?:dup|ect|ize|nd(?:(?:bk)?)|tr|ubsc|wap)|t(?:a(?:bmat|lly)|oby|race)|unmark|va(?:lue|r))\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\b(any|case|e(?:nd(?:case|every|if(?:(?:else)?)|repeat|suspend|until|while)|very)|if(?:(?:else)?)|repeat|suspend|until|while)\b", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\d+(\s*|\.$|$)", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[+-]?\d*\.\d+(E[-+]?\d+)?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[+-]?\d+\.\d*(E[-+]?\d+)?", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(<>|=>|[()|:;,.'`]|[{}]|[%^]|[&?])", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\s+\b", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[\w-]+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });

        inner.states.insert("root".to_string(), root_rules);

        UcodeLexer { inner }
    }
}

impl Lexer for UcodeLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
