// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: UrbiscriptLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated UrbiscriptLexer lexer.
pub struct UrbiscriptLexer {
    inner: RegexLexer,
}

impl UrbiscriptLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("UrbiScript");
        inner.aliases = vec![
            "urbiscript",
        ];
        inner.filenames = vec![
            "*.u",
        ];
        inner.mimetypes = vec![
            "application/x-urbiscript",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\s+", Token::TEXT).unwrap(), action: LexerAction::token(Token::TEXT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"//.*?\n", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"/\*", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("comment".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(every|for|loop|while)(?:;|&|\||,)", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(a(?:(?:(?:sser)?)t)|break|c(?:a(?:se|tch)|losure|o(?:mpl|ntinue))|default|e(?:lse|num|very|xternal)|f(?:inally|or|reezeif)|if|new|onleave|return|s(?:topif|witch)|t(?:h(?:is|row)|imeout|ry)|w(?:aituntil|h(?:enever|ile)))\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(a(?:sm|uto)|bool|c(?:har|onst_cast)|d(?:elete|ouble|ynamic_cast)|ex(?:p(?:(?:lici|or)t)|tern)|f(?:loat|riend)|goto|in(?:line|t)|long|mutable|namespace|re(?:gister|interpret_cast)|s(?:hort|i(?:gned|zeof)|t(?:(?:atic_cas|ruc)t))|t(?:emplate|ype(?:def|id|name))|u(?:n(?:ion|signed)|sing)|v(?:irtual|olatile)|wchar_t)\b", Token::KEYWORD_RESERVED).unwrap(), action: LexerAction::token(Token::KEYWORD_RESERVED) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(emit|foreach|internal|loopn|static)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(private|protected|public)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(var|do|const|function|class)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(true|false|nil|void)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(B(?:arrier|inary|oolean)|C(?:allMessage|hannel|o(?:de|mparable|nt(?:ainer|rol)))|D(?:ate|i(?:(?:ctiona|recto)ry)|uration)|E(?:numeration|vent|x(?:ception|ecutable))|F(?:i(?:(?:(?:nalizab)?)le)|loat|ormat(?:Info|ter))|G(?:lobal|roup)|Hash|I(?:nputStream|oService)|Job|Kernel|L(?:azy|ist|o(?:adable|bby|cation|gger))|M(?:ath|utex)|O(?:bject|rderable|utputStream)|P(?:a(?:ir|t(?:h|tern))|osition|r(?:imitive|o(?:cess|file))|seudoLazy|ubSub)|R(?:angeIterable|egexp)|S(?:e(?:maphore|rver)|ingleton|ocket|t(?:ackFrame|r(?:eam|ing))|ystem)|T(?:ag|imeout|r(?:a(?:ceable|jectoryGenerator)|iplet)|uple)|U(?:Object|Va(?:lue|r))|nil)\b", Token::NAME_BUILTIN).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?:this)\b", Token::NAME_BUILTIN_PSEUDO).unwrap(), action: LexerAction::token(Token::NAME_BUILTIN_PSEUDO) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?:[-=+*%/<>~^:]+|\.&?|\|\||&&)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?:and_eq|and|bitand|bitor|in|not|not_eq|or_eq|or|xor_eq|xor)\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[{}\[\]()]+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?:;|\||,|&|\?|!)+", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[$a-zA-Z_]\w*", Token::NAME_OTHER).unwrap(), action: LexerAction::token(Token::NAME_OTHER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"0x[0-9a-fA-F]+", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?:[0-9]+(?:(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)?((?:rad|deg|grad)|(?:ms|s|min|h|d))?)\b", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::Push("string.double".to_string()) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"'", Token::STRING_SINGLE).unwrap(), action: LexerAction::Push("string.single".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        // State: string.double
        inner.states.insert("string.double".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"(\\\\|\\[^\\]|[^"\\])*?""##, Token::STRING_DOUBLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: string.single
        inner.states.insert("string.single".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(\\\\|\\[^\\]|[^'\\])*?'", Token::STRING_SINGLE).unwrap(), action: LexerAction::PopN(1) },
        ]);

        // State: comment
        inner.states.insert("comment".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[^*/]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
            LexerRule { pattern: TokenPattern::new(r"/\*", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\*/", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"[*/]", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) },
        ]);

        UrbiscriptLexer { inner }
    }
}

impl Lexer for UrbiscriptLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
