// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: VGLLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated VGLLexer lexer.
pub struct VGLLexer {
    inner: RegexLexer,
}

impl VGLLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("VGL");
        inner.aliases = vec![
            "vgl",
        ];
        inner.filenames = vec![
            "*.rpf",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"\{[^}]*\}", Token::COMMENT_MULTILINE).unwrap(), action: LexerAction::token(Token::COMMENT_MULTILINE) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"declare", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(if|then|else|endif|while|do|endwhile|and|or|prompt|object|create|on|line|with|global|routine|value|endroutine|constant|global|set|join|library|compile_option|file|exists|create|copy|delete|enable|windows|name|notprotected)(?! *[=<>.,()])", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(true|false|null|empty|error|locked)", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[~^*#!%&\[\]()<>|+=:;,./?-]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r##""[^"]*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[0-9][0-9]*(\.[0-9]+(e[+\-]?[0-9]+)?)?", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) });
            root_rules.push(LexerRule { pattern: TokenPattern::new(r"[a-z_$][\w$]*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) });

        inner.states.insert("root".to_string(), root_rules);

        VGLLexer { inner }
    }
}

impl Lexer for VGLLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
