// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: XtlangLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated XtlangLexer lexer.
pub struct XtlangLexer {
    inner: RegexLexer,
}

impl XtlangLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("xtlang");
        inner.aliases = vec![
            "extempore",
        ];
        inner.filenames = vec![
            "*.xtm",
        ];

        // State: xtlang
        inner.states.insert("xtlang".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\(", Token::PUNCTUATION).unwrap(), action: LexerAction::Push("root".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"\)", Token::PUNCTUATION).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-func\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-val\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-type\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-alias\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-poly\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-lib\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-dylib\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-lib-func\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(?<=bind-lib-val\s)[\w.!-]+", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r":[]{}[\w<>,*/|!-]+", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"(<[]{}[\w<>,*/|!-]+>|\|[]{}[\w<>,*/|!-]+\||/[]{}[\w<>,*/|!-]+/|[]{}[\w<>,*/|!-]+\*)\**", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\()(c(?:(?:as|onver)t)|do(?:loop|times)|letz|memzone)", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\()(<(?:[<>])|>>|a(?:cos|fill!|lloc|ng\-names|r(?:ef(?:(?:\-ptr)?)|ray(?:(?:\-(?:fill!|ref(?:(?:\-ptr)?)|set!))?))|s(?:et!|in)|tan)|b(?:itcast|or)|c(?:allback|eiling|l(?:osure\-(?:ref|set!)|run\->)|os|ref|set!)|dtof|exp(?:(?:t)?)|f(?:loor|ree|tod)|h(?:(?:(?:eap\-)?)alloc)|i(?:1to(?:i(?:32|64|8)|[df])|32to(?:i(?:64|[18])|[df])|64to(?:i(?:32|[18])|[df])|8to(?:i(?:1|32|64)|[df])|fret|mpc_null)|l(?:ist|lvm_(?:(?:(?:s)?)printf)|og)|m(?:ake\-(?:array|env(?:(?:\-zone)?)|tuple)|emzone)|n(?:il|ow|ull)|p(?:dref|fill!|o(?:inter\-(?:fill!|ref(?:(?:\-ptr)?)|set!)|p_zone)|r(?:ef(?:(?:\-ptr)?)|intf)|set!|ush_zone)|r(?:et\->|ound)|s(?:alloc|chedule|in|printf|qrt|tack\-alloc)|t(?:an|bind|fill!|oString|r(?:ef(?:(?:\-ptr)?)|uncate)|set!|uple(?:(?:\-(?:fill!|ref(?:(?:\-ptr)?)|set!))?))|v(?:ector\-fill!|fill!|oid|ref|set!)|z(?:(?:(?:one\-)?)alloc)|[&~])", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"[\w.!-]+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
        ]);

        // State: scheme
        inner.states.insert("scheme".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"'[\w!$%&*+,/:<=>?@^~|-]+", Token::STRING_SYMBOL).unwrap(), action: LexerAction::token(Token::STRING_SYMBOL) },
            LexerRule { pattern: TokenPattern::new(r#"#\\([()/'\"._!§$%& ?=+-]|[a-zA-Z0-9]+)"#, Token::STRING_CHAR).unwrap(), action: LexerAction::token(Token::STRING_CHAR) },
            LexerRule { pattern: TokenPattern::new(r"('|#|`|,@|,|\.)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\()(case|d(?:elay|o)|eval|let(?:\*|rec)|qu(?:(?:(?:asiqu)?)ote)|unquote(?:(?:\-splicing)?))", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\()(c(?:all(?:\-with\-(?:current\-continuation|input\-file|output\-file|values)|/cc)|har(?:\-(?:>integer|alphabetic\?|ci(?:(?:(?:[<>])=|[<=>])\?)|downcase|lower\-case\?|numeric\?|ready\?|up(?:case|per\-case\?)|whitespace\?)|(?:(?:(?:[<>])=|[<=>])?)\?)|lose\-(?:(?:in|out)put\-port)|omplex\?|urrent\-(?:(?:in|out)put\-port))|d(?:enominator|isplay|ynamic\-wind)|e(?:of\-object\?|q(?:(?:(?:ual|v)?)\?)|ven\?|x(?:act(?:\->inexact|\?)|p(?:(?:t)?)))|force|gcd|i(?:mag\-part|n(?:exact(?:\->exact|\?)|put\-port\?|te(?:ger(?:\->char|\?)|raction\-environment)))|l(?:cm|ist(?:\-(?:>(?:string|vector)|ref|tail)|\?)|oad)|m(?:a(?:gnitude|ke\-(?:polar|rectangular|string|vector))|em(?:[qv]))|n(?:e(?:gative\?|wline)|u(?:ll\-environment|m(?:ber(?:\->string|\?)|erator)))|o(?:dd\?|pen\-(?:(?:in|out)put\-file)|utput\-port\?)|p(?:air\?|eek\-char|(?:o(?:rt|sitive)|rocedure)\?)|quotient|r(?:ational(?:\?|ize)|e(?:a(?:d(?:(?:\-char)?)|l(?:\-part|\?))|mainder))|s(?:cheme\-report\-environment|et\-c(?:(?:[ad])r!)|tring(?:(?:\-(?:>(?:list|number|symbol)|append|c(?:i(?:(?:(?:[<>])=|[<=>])\?)|opy)|fill!|length|ref|set!)|(?:(?:(?:[<>])=|[<=>])?)\?)?)|ymbol(?:\->string|\?))|tr(?:anscript\-o(?:ff|n)|uncate)|v(?:alues|ector(?:(?:\-(?:>list|fill!|length)|\?)?))|w(?:ith\-(?:(?:input\-from|output\-to)\-file)|rite(?:(?:\-char)?))|zero\?)", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"[\w!$%&*+,/:<=>?@^~|-]+", Token::NAME_VARIABLE).unwrap(), action: LexerAction::token(Token::NAME_VARIABLE) },
        ]);

        // State: common
        inner.states.insert("common".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r";.*$", Token::COMMENT_SINGLE).unwrap(), action: LexerAction::token(Token::COMMENT_SINGLE) },
            LexerRule { pattern: TokenPattern::new(r"-?\d+\.\d+", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"-?\d+", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"(#b|#o|#x)[\d.]+", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r##""(\\\\|\\[^\\]|[^"\\])*""##, Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
            LexerRule { pattern: TokenPattern::new(r"(#t|#f)", Token::NAME_CONSTANT).unwrap(), action: LexerAction::token(Token::NAME_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\()(and|begin|cond|define|else|for\-each|if|l(?:ambda|et)|map|or|set!)", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(?<=\()(<=|>=|a(?:bs|cos|ngle|pp(?:end|ly)|s(?:in|s(?:oc|[qv]))|tan)|boolean\?|c(?:a(?:a(?:(?:(?:a(?:[ad])|d(?:[ad])|[ad])?)r)|d(?:(?:(?:a(?:[ad])|d(?:[ad])|[ad])?)r)|llback|r)|d(?:(?:(?:a(?:a(?:[ad])|d(?:[ad])|[ad])|d(?:a(?:[ad])|d(?:[ad])|[ad])|[ad])?)r)|eiling|o(?:(?:(?:n)?)s))|floor|l(?:ength|ist|og)|m(?:ax|ember|in|odulo)|n(?:o(?:[tw])|ull\?)|println|r(?:andom|everse|ound)|s(?:in|qrt|ubstring)|tan|[%*+\-/<=>])", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) },
            LexerRule { pattern: TokenPattern::new(r"(\(|\))", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"(?<=\()(bind\-(?:alias|dylib|func|lib(?:(?:\-(?:func|val))?)|poly|type|val))\b", Token::KEYWORD).unwrap(), action: LexerAction::Push("xtlang".to_string()) });

        inner.states.insert("root".to_string(), root_rules);

        XtlangLexer { inner }
    }
}

impl Lexer for XtlangLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
