// AUTO-GENERATED by generators/gen_lexers.py — DO NOT EDIT BY HAND
// Lexer: ZeekLexer

use crate::token::Token;
use crate::lexer::{Lexer, RegexLexer, LexerRule, LexerAction};
use crate::scanner::TokenPattern;

/// Auto-generated ZeekLexer lexer.
pub struct ZeekLexer {
    inner: RegexLexer,
}

impl ZeekLexer {
    pub fn new() -> Self {
        let mut inner = RegexLexer::new("Zeek");
        inner.aliases = vec![
            "zeek",
            "bro",
        ];
        inner.filenames = vec![
            "*.zeek",
            "*.bro",
        ];

        // Root state
        let mut root_rules: Vec<LexerRule> = Vec::new();

            root_rules.push(LexerRule { pattern: TokenPattern::new(r"((?:[A-Za-z_]\w*)(?:::(?:[A-Za-z_]\w*))*)(?=\s*\()", Token::NAME_FUNCTION).unwrap(), action: LexerAction::token(Token::NAME_FUNCTION) });

        inner.states.insert("root".to_string(), root_rules);

        // State: whitespace
        inner.states.insert("whitespace".to_string(), vec![
        ]);

        // State: comments
        inner.states.insert("comments".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"#.*$", Token::COMMENT).unwrap(), action: LexerAction::token(Token::COMMENT) },
        ]);

        // State: directives
        inner.states.insert("directives".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"@(load-plugin|load-sigs|load|unload)\b.*$", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
            LexerRule { pattern: TokenPattern::new(r"@(DEBUG|DIR|FILENAME|deprecated|if|ifdef|ifndef|else|endif)\b", Token::COMMENT_PREPROC).unwrap(), action: LexerAction::token(Token::COMMENT_PREPROC) },
        ]);

        // State: attributes
        inner.states.insert("attributes".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"&(add_func|create_expire|de(?:fault|lete_func|precated)|e(?:ncrypt|rror_handler|xpire_func)|log|mergeable|optional|p(?:ersistent|riority)|r(?:aw_output|e(?:ad_expire|def)|otate_(?:interval|size))|synchronized|type_column|write_expire)\b", Token::KEYWORD_PSEUDO).unwrap(), action: LexerAction::token(Token::KEYWORD_PSEUDO) },
        ]);

        // State: types
        inner.states.insert("types".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(a(?:ddr|ny)|bool|count|double|e(?:num|vent)|f(?:ile|unction)|hook|int(?:(?:erval)?)|p(?:attern|ort)|record|s(?:et|tring|ubnet)|t(?:(?:abl|im)e)|vector)\b", Token::KEYWORD_TYPE).unwrap(), action: LexerAction::token(Token::KEYWORD_TYPE) },
        ]);

        // State: keywords
        inner.states.insert("keywords".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"(add|break|c(?:(?:as|ontinu)e)|de(?:fault|lete)|e(?:lse|xport)|f(?:allthrough|or)|if|next|re(?:def|turn)|s(?:chedule|witch)|timeout|wh(?:en|ile))\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(print)\b", Token::KEYWORD).unwrap(), action: LexerAction::token(Token::KEYWORD) },
            LexerRule { pattern: TokenPattern::new(r"(global|local|const|option)\b", Token::KEYWORD_DECLARATION).unwrap(), action: LexerAction::token(Token::KEYWORD_DECLARATION) },
        ]);

        // State: literals
        inner.states.insert("literals".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::Push("string".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"/(?=.*/)", Token::STRING_REGEX).unwrap(), action: LexerAction::Push("regex".to_string()) },
            LexerRule { pattern: TokenPattern::new(r"(T|F)\b", Token::KEYWORD_CONSTANT).unwrap(), action: LexerAction::token(Token::KEYWORD_CONSTANT) },
            LexerRule { pattern: TokenPattern::new(r"\d{1,5}/(udp|tcp|icmp|unknown)\b", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r"(\d{1,3}.){3}(\d{1,3})\b", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r"\[([0-9a-fA-F]{0,4}:){2,7}([0-9a-fA-F]{0,4})?((\d{1,3}.){3}(\d{1,3}))?\]", Token::NUMBER).unwrap(), action: LexerAction::token(Token::NUMBER) },
            LexerRule { pattern: TokenPattern::new(r"0[xX][0-9a-fA-F]+\b", Token::NUMBER_HEX).unwrap(), action: LexerAction::token(Token::NUMBER_HEX) },
            LexerRule { pattern: TokenPattern::new(r"((\d*\.?\d+)|(\d+\.?\d*))([eE][-+]?\d+)?\s*(day|hr|min|sec|msec|usec)s?\b", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"((\d*\.?\d+)|(\d+\.?\d*))([eE][-+]?\d+)?\b", Token::NUMBER_FLOAT).unwrap(), action: LexerAction::token(Token::NUMBER_FLOAT) },
            LexerRule { pattern: TokenPattern::new(r"(\d+)\b", Token::NUMBER_INTEGER).unwrap(), action: LexerAction::token(Token::NUMBER_INTEGER) },
            LexerRule { pattern: TokenPattern::new(r"[A-Za-z0-9][-A-Za-z0-9]*(\.[A-Za-z0-9][-A-Za-z0-9]*)+", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: operators
        inner.states.insert("operators".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[!%*/+<=>~|&^-]", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"([-+=&|]{2}|[+=!><-]=)", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
            LexerRule { pattern: TokenPattern::new(r"(in|as|is|of)\b", Token::OPERATOR_WORD).unwrap(), action: LexerAction::token(Token::OPERATOR_WORD) },
            LexerRule { pattern: TokenPattern::new(r"\??\$", Token::OPERATOR).unwrap(), action: LexerAction::token(Token::OPERATOR) },
        ]);

        // State: punctuation
        inner.states.insert("punctuation".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[{}()\[\],;.]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
            LexerRule { pattern: TokenPattern::new(r"[?:]", Token::PUNCTUATION).unwrap(), action: LexerAction::token(Token::PUNCTUATION) },
        ]);

        // State: identifiers
        inner.states.insert("identifiers".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"[a-zA-Z_]\w*", Token::NAME).unwrap(), action: LexerAction::token(Token::NAME) },
        ]);

        // State: string
        inner.states.insert("string".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\.", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r"%-?[0-9]*(\.[0-9]+)?[DTd-gsx]", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r##"""##, Token::STRING).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r".", Token::STRING).unwrap(), action: LexerAction::token(Token::STRING) },
        ]);

        // State: regex
        inner.states.insert("regex".to_string(), vec![
            LexerRule { pattern: TokenPattern::new(r"\\.", Token::STRING_ESCAPE).unwrap(), action: LexerAction::token(Token::STRING_ESCAPE) },
            LexerRule { pattern: TokenPattern::new(r"/", Token::STRING_REGEX).unwrap(), action: LexerAction::PopN(1) },
            LexerRule { pattern: TokenPattern::new(r".", Token::STRING_REGEX).unwrap(), action: LexerAction::token(Token::STRING_REGEX) },
        ]);

        ZeekLexer { inner }
    }
}

impl Lexer for ZeekLexer {
    fn get_tokens(&self, code: &str) -> Vec<(Token, String)> {
        self.inner.get_tokens(code)
    }

    fn name(&self) -> &str {
        &self.inner.name
    }

    fn aliases(&self) -> &[&str] {
        &self.inner.aliases
    }

    fn filenames(&self) -> &[&str] {
        &self.inner.filenames
    }

    fn mimetypes(&self) -> &[&str] {
        &self.inner.mimetypes
    }
}
